apiVersion: v1
kind: ConfigMap
metadata:
  name: web-ui-config
data:
  API_BASE_URL: "https://grill-stats.homelab.local/api"
  WS_BASE_URL: "wss://grill-stats.homelab.local/ws"
  ENVIRONMENT: "prod-lab"
  VERSION: "v1.0.0"
  NGINX_WORKER_PROCESSES: "auto"
  NGINX_WORKER_CONNECTIONS: "2048"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  LOG_LEVEL: "INFO"
  RATE_LIMIT_ATTEMPTS: "5"
  RATE_LIMIT_WINDOW: "900"
  RATE_LIMIT_LOCKOUT: "3600"
  SESSION_TIMEOUT: "86400"
  TOKEN_EXPIRY: "3600"
  REFRESH_TOKEN_EXPIRY: "604800"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: historical-data-service-config
data:
  LOG_LEVEL: "INFO"
  CACHE_TTL: "600"
  MAX_QUERY_RANGE_DAYS: "30"
  AGGREGATION_WINDOW: "5m"
  RETENTION_POLICY: "30d"
  QUERY_TIMEOUT: "30s"
  MAX_CONCURRENT_QUERIES: "10"