apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - device-service.yaml
  - temperature-service.yaml
  - homeassistant-service.yaml
  - notification-service.yaml
  - data-processing-service.yaml

commonLabels:
  app.kubernetes.io/name: grill-stats
  app.kubernetes.io/part-of: grill-stats
  app.kubernetes.io/managed-by: kustomize

namespace: grill-stats
