apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: grill-stats
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: database-credentials
type: Opaque
stringData:
  # These values should be replaced in overlays for different environments
  # You can use kustomize secretGenerator to manage these securely
  DB_USER: "postgres"
  DB_PASSWORD: "changeme"
  DB_HOST: "postgres.grill-stats.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "grill_stats"
  DATABASE_URL: "postgresql://postgres:changeme@postgres.grill-stats.svc.cluster.local:5432/grill_stats"
