apiVersion: v1
kind: Secret
metadata:
  name: flask-app-secrets
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: grill-stats
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: app-secrets
type: Opaque
stringData:
  # These values should be replaced in overlays for different environments
  # You can use kustomize secretGenerator to manage these securely
  SECRET_KEY: "changeme-with-a-secure-random-key-in-production"

  # Admin user credentials for initial setup
  ADMIN_EMAIL: "admin@example.com"
  ADMIN_PASSWORD: "changeme-with-secure-password"
  ADMIN_NAME: "Administrator"
