apiVersion: v1
kind: Secret
metadata:
  name: homeassistant-credentials
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: grill-stats
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: api-credentials
type: Opaque
stringData:
  # These values should be replaced in overlays for different environments
  # You can use kustomize secretGenerator to manage these securely
  HOMEASSISTANT_URL: "http://homeassistant:8123"
  HOMEASSISTANT_TOKEN: "changeme"
