apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - thermoworks-api-secret.yaml
  - homeassistant-secret.yaml
  - database-secret.yaml
  - redis-secret.yaml
  - flask-secret.yaml
