apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.example.com:587'
      smtp_from: 'alerts@grill-stats.example.com'
      smtp_auth_username: 'alerts@grill-stats.example.com'
      smtp_auth_password: 'password'

    route:
      group_by: ['alertname', 'database']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: 'email'
      routes:
        - match:
            severity: critical
          receiver: 'email'
          continue: true
        - match_re:
            severity: ^(warning|info)$
          receiver: 'slack'

    receivers:
      - name: 'email'
        email_configs:
          - to: 'admin@example.com'
            send_resolved: true

      - name: 'slack'
        slack_configs:
          - api_url: 'https://hooks.slack.com/services/REPLACE_WITH_ACTUAL_WEBHOOK'
            send_resolved: true
            channel: '#alerts'
            title: '{{ .GroupLabels.alertname }}'
            text: >-
              {{ range .Alerts }}
                *Alert:* {{ .Annotations.summary }}
                *Description:* {{ .Annotations.description }}
                *Severity:* {{ .Labels.severity }}
                *Database:* {{ .Labels.database }}
              {{ end }}

    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'database']
