apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: monitoring
spec:
  selector:
    app.kubernetes.io/name: alertmanager
  ports:
    - name: http
      port: 9093
      targetPort: http
  type: ClusterIP
