apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: grill-stats
  labels:
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: monitoring
type: Opaque
stringData:
  postgres-uri: "postgresql://postgres:postgres@postgres.grill-stats.svc.cluster.local:5432/grill_stats?sslmode=disable"
  redis-password: ""  # Update with actual password if Redis is password-protected
