apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
