apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: monitoring
spec:
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - name: http
      port: 3000
      targetPort: http
  type: ClusterIP
