apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: monitoring
type: Opaque
stringData:
  password: admin  # Change this in production
