apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: postgres-exporter
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres-exporter
        app.kubernetes.io/part-of: grill-stats
        app.kubernetes.io/component: monitoring
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
    spec:
      containers:
        - name: postgres-exporter
          image: quay.io/prometheuscommunity/postgres-exporter:v0.14.0
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: postgres-uri
            - name: PG_EXPORTER_EXTEND_QUERY_PATH
              value: /etc/postgres_exporter/queries.yaml
          ports:
            - name: metrics
              containerPort: 9187
          volumeMounts:
            - name: postgres-exporter-queries
              mountPath: /etc/postgres_exporter/queries.yaml
              subPath: queries.yaml
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: postgres-exporter-queries
          configMap:
            name: postgres-exporter-queries
