apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: monitoring
