apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grill-monitoring-staging

bases:
- ../../base

resources:
- namespace.yaml

patches:
- path: patches/ingress-patch.yaml

configMapGenerator:
- name: grill-monitoring-config
  behavior: merge
  literals:
  - SYNC_INTERVAL="180"  # 3 minutes for staging environment

secretGenerator:
- name: grill-monitoring-secrets
  behavior: merge
  envs:
  - secrets/staging.env  # Will contain staging environment secrets