apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grill-stats-staging

bases:
- ../../base

resources:
- namespace.yaml
- network-policies-staging.yaml

patches:
- path: patches/ingress-patch.yaml
- path: patches/grill-stats-ingress-patch.yaml

configMapGenerator:
- name: grill-stats-config
  behavior: merge
  literals:
  - SYNC_INTERVAL="180"  # 3 minutes for staging environment

secretGenerator:
- name: grill-stats-secrets
  behavior: merge
  envs:
  - secrets/staging.env  # Will contain staging environment secrets