apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup
spec:
  schedule: "0 */4 * * *"  # Every 4 hours for testing
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgresql-backup
            resources:
              requests:
                memory: "128Mi"
                cpu: "50m"
                ephemeral-storage: "1Gi"
              limits:
                memory: "512Mi"
                cpu: "200m"
                ephemeral-storage: "5Gi"
            env:
            - name: BACKUP_RETENTION_DAYS
              value: "7"
            - name: BACKUP_REMOTE_SYNC
              value: "false"
            - name: LOG_LEVEL
              value: "DEBUG"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: influxdb-backup
spec:
  schedule: "15 */4 * * *"  # Every 4 hours, offset by 15 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: influxdb-backup
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
                ephemeral-storage: "2Gi"
              limits:
                memory: "1Gi"
                cpu: "500m"
                ephemeral-storage: "10Gi"
            env:
            - name: BACKUP_RETENTION_DAYS
              value: "3"
            - name: BACKUP_REMOTE_SYNC
              value: "false"
            - name: LOG_LEVEL
              value: "DEBUG"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: redis-backup
spec:
  schedule: "30 */4 * * *"  # Every 4 hours, offset by 30 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: redis-backup
            resources:
              requests:
                memory: "64Mi"
                cpu: "25m"
                ephemeral-storage: "500Mi"
              limits:
                memory: "256Mi"
                cpu: "100m"
                ephemeral-storage: "2Gi"
            env:
            - name: BACKUP_RETENTION_DAYS
              value: "3"
            - name: BACKUP_REMOTE_SYNC
              value: "false"
            - name: LOG_LEVEL
              value: "DEBUG"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-verification
spec:
  schedule: "45 */4 * * *"  # Every 4 hours, offset by 45 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-verification
            resources:
              requests:
                memory: "64Mi"
                cpu: "25m"
                ephemeral-storage: "500Mi"
              limits:
                memory: "256Mi"
                cpu: "100m"
                ephemeral-storage: "2Gi"
            env:
            - name: LOG_LEVEL
              value: "DEBUG"
