version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: grill_stats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database-init:/docker-entrypoint-initdb.d
    networks:
      - grill-stats-network

  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - grill-stats-network

  # Auth Service
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=grill_stats
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-jwt-secret-key
      - SECRET_KEY=your-secret-key
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - redis
    networks:
      - grill-stats-network

  # Device Service
  device-service:
    build:
      context: ./services/device-service
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=grill_stats
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-jwt-secret-key
      - THERMOWORKS_CLIENT_ID=${THERMOWORKS_CLIENT_ID}
      - THERMOWORKS_CLIENT_SECRET=${THERMOWORKS_CLIENT_SECRET}
      - THERMOWORKS_REDIRECT_URI=${THERMOWORKS_REDIRECT_URI}
      - THERMOWORKS_BASE_URL=${THERMOWORKS_BASE_URL}
      - THERMOWORKS_AUTH_URL=${THERMOWORKS_AUTH_URL}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - grill-stats-network

  # Web UI
  web-ui:
    build:
      context: ./services/web-ui
      dockerfile: Dockerfile
    environment:
      - REACT_APP_AUTH_SERVICE_URL=http://localhost:8082
      - REACT_APP_DEVICE_SERVICE_URL=http://localhost:8080
      - REACT_APP_TEMPERATURE_SERVICE_URL=http://localhost:8081
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - device-service
    networks:
      - grill-stats-network

volumes:
  postgres_data:

networks:
  grill-stats-network:
    driver: bridge
