version: '3.8'

services:
  # Postgres for database operations
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: grill_stats_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d grill_stats_test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - grill-stats-test-network

  # Redis for caching and pub/sub
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - grill-stats-test-network

  # Device Service
  device-service:
    build:
      context: ./services/device-service
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=grill_stats_test
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=test-jwt-secret-key-123456789
      - MOCK_REDIS=false
      - DEBUG=true
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["python", "main_minimal.py"]
    networks:
      - grill-stats-test-network

networks:
  grill-stats-test-network:
    driver: bridge
