apiVersion: v1
kind: Pod
metadata:
  name: test-latest-image
  namespace: grill-monitoring-dev
spec:
  containers:
  - name: test
    image: docker.io/lordmuffin/grill-stats-device-service:latest
    imagePullPolicy: Always
    command: ["sh", "-c", "echo 'Image info:' && cat /etc/os-release && echo 'App info:' && ls -la /app/ && sleep 300"]
  restartPolicy: Never
