apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/namespace

patchesStrategicMerge:
  - namespace.yaml
  - resourcequota.yaml
  - limitrange.yaml

commonLabels:
  environment: staging

namespace: grill-stats-staging

namePrefix: staging-
