apiVersion: v1
kind: ResourceQuota
metadata:
  name: grill-stats-quota
  namespace: grill-stats-staging
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 12Gi
    limits.cpu: "12"
    limits.memory: 24Gi
    persistentvolumeclaims: "15"
    pods: "40"
    services: "18"
    services.loadbalancers: "2"
    secrets: "25"
    configmaps: "25"
