apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: device-service-binding
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: device-service
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/managed-by: kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: device-service-role
subjects:
  - kind: ServiceAccount
    name: device-service
    namespace: grill-stats
