apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - microservice-role.yaml
  - device-service-role.yaml
  - temperature-service-role.yaml
  - device-service-binding.yaml
  - temperature-service-binding.yaml
  - homeassistant-service-binding.yaml
  - notification-service-binding.yaml
  - data-processing-service-binding.yaml

commonLabels:
  app.kubernetes.io/name: grill-stats
  app.kubernetes.io/part-of: grill-stats
  app.kubernetes.io/managed-by: kustomize

namespace: grill-stats
