apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: temperature-service-role
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: temperature-service
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/managed-by: kustomize
rules:
  # All standard microservice permissions
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]
  # Temperature service specific permissions for event creation
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
