apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: grill-stats-secrets-dev-lab
  annotations:
    config.kubernetes.io/local-config: "true"

namespace: grill-stats-dev

# Base resources from parent directory
resources:
  - ../

  # Dev-lab specific resources
  - environment-secrets-1password.yaml
  - rbac-dev-1password.yaml

commonLabels:
  app.kubernetes.io/name: grill-stats
  app.kubernetes.io/component: secrets
  app.kubernetes.io/part-of: grill-stats-platform
  app.kubernetes.io/managed-by: onepassword-connect
  app.kubernetes.io/version: dev-lab
  environment: dev-lab
  onepassword.com/managed: "true"

commonAnnotations:
  config.kubernetes.io/local-config: "true"
  onepassword.com/vault: "grill-stats-dev"
  onepassword.com/environment: "dev-lab"
  onepassword.com/version: "v1.0.0-dev"
  deployment.kubernetes.io/revision: "1"

# Override namespace for dev environment
namespace: grill-stats-dev

# Configuration for dev environment
configMapGenerator:
- name: grill-stats-secrets-config
  behavior: merge
  literals:
    - environment=dev-lab
    - vault-name=grill-stats-dev
    - secret-rotation-days=30
    - backup-enabled=false
    - monitoring-enabled=true
    - audit-enabled=true
    - debug-enabled=true
    - log-level=DEBUG

# Secret generator for dev-specific configurations
secretGenerator:
- name: grill-stats-common-config
  behavior: merge
  literals:
    - log-level=DEBUG
    - health-check-interval=10
    - metrics-port=9090
    - debug-enabled=true
    - dev-mode=true

# Patches for dev environment
patchesStrategicMerge:
- |
  apiVersion: v1
  kind: Secret
  metadata:
    name: auth-service-secrets
    namespace: grill-stats-dev
  stringData:
    debug-enabled: "true"
    log-level: "DEBUG"
    rate-limit-enabled: "false"
    dev-mode: "true"
- |
  apiVersion: v1
  kind: Secret
  metadata:
    name: device-service-secrets
    namespace: grill-stats-dev
  stringData:
    debug-enabled: "true"
    log-level: "DEBUG"
    device-discovery-interval: "30"
    dev-mode: "true"
- |
  apiVersion: v1
  kind: Secret
  metadata:
    name: temperature-service-secrets
    namespace: grill-stats-dev
  stringData:
    debug-enabled: "true"
    log-level: "DEBUG"
    temperature-sampling-interval: "1"
    dev-mode: "true"
- |
  apiVersion: v1
  kind: Secret
  metadata:
    name: historical-data-service-secrets
    namespace: grill-stats-dev
  stringData:
    debug-enabled: "true"
    log-level: "DEBUG"
    query-timeout: "60"
    dev-mode: "true"
- |
  apiVersion: v1
  kind: Secret
  metadata:
    name: encryption-service-secrets
    namespace: grill-stats-dev
  stringData:
    debug-enabled: "true"
    log-level: "DEBUG"
    audit-enabled: "false"
    dev-mode: "true"
- |
  apiVersion: v1
  kind: Secret
  metadata:
    name: web-ui-secrets
    namespace: grill-stats-dev
  stringData:
    debug-enabled: "true"
    dev-mode: "true"
    hot-reload: "true"
    analytics-enabled: "false"

# Replacements for dev environment
replacements:
- source:
    kind: ConfigMap
    name: grill-stats-secrets-config
    fieldPath: data.vault-name
  targets:
  - select:
      kind: OnePasswordItem
    fieldPaths:
    - spec.itemPath
    options:
      delimiter: "/"
      index: 1

# JSON patches for dev-specific modifications
patchesJson6902:
- target:
    group: onepassword.com
    version: v1
    kind: OnePasswordItem
    name: auth-service-secrets-1password
  patch: |-
    - op: replace
      path: /spec/itemPath
      value: vaults/grill-stats-dev/items/auth-service-secrets
- target:
    group: onepassword.com
    version: v1
    kind: OnePasswordItem
    name: device-service-secrets-1password
  patch: |-
    - op: replace
      path: /spec/itemPath
      value: vaults/grill-stats-dev/items/device-service-secrets
- target:
    group: onepassword.com
    version: v1
    kind: OnePasswordItem
    name: temperature-service-secrets-1password
  patch: |-
    - op: replace
      path: /spec/itemPath
      value: vaults/grill-stats-dev/items/temperature-service-secrets
- target:
    group: onepassword.com
    version: v1
    kind: OnePasswordItem
    name: historical-data-service-secrets-1password
  patch: |-
    - op: replace
      path: /spec/itemPath
      value: vaults/grill-stats-dev/items/historical-data-service-secrets
- target:
    group: onepassword.com
    version: v1
    kind: OnePasswordItem
    name: encryption-service-secrets-1password
  patch: |-
    - op: replace
      path: /spec/itemPath
      value: vaults/grill-stats-dev/items/encryption-service-secrets
- target:
    group: onepassword.com
    version: v1
    kind: OnePasswordItem
    name: web-ui-secrets-1password
  patch: |-
    - op: replace
      path: /spec/itemPath
      value: vaults/grill-stats-dev/items/web-ui-secrets
- target:
    group: onepassword.com
    version: v1
    kind: OnePasswordItem
    name: postgresql-secrets-1password
  patch: |-
    - op: replace
      path: /spec/itemPath
      value: vaults/grill-stats-dev/items/postgresql-secrets
- target:
    group: onepassword.com
    version: v1
    kind: OnePasswordItem
    name: influxdb-secrets-1password
  patch: |-
    - op: replace
      path: /spec/itemPath
      value: vaults/grill-stats-dev/items/influxdb-secrets
- target:
    group: onepassword.com
    version: v1
    kind: OnePasswordItem
    name: redis-secrets-1password
  patch: |-
    - op: replace
      path: /spec/itemPath
      value: vaults/grill-stats-dev/items/redis-secrets
- target:
    group: onepassword.com
    version: v1
    kind: OnePasswordItem
    name: timescaledb-secrets-1password
  patch: |-
    - op: replace
      path: /spec/itemPath
      value: vaults/grill-stats-dev/items/timescaledb-secrets

# Generators for dev environment
generators:
- |
  apiVersion: builtin
  kind: ConfigMapGenerator
  metadata:
    name: dev-environment-config
  literals:
    - environment=dev-lab
    - cluster-name=grill-stats-dev
    - region=homelab-dev
    - deployment-time=$(date -u +%Y%m%d%H%M%S)
    - debug-enabled=true
    - log-level=DEBUG
