---
# Dev Lab Environment Secrets Management Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grill-stats-secrets-manager-dev
  namespace: grill-stats-dev
  labels:
    app: grill-stats
    component: secrets
    environment: dev-lab
    managed-by: onepassword-connect
  annotations:
    onepassword.com/service-account: "true"
    onepassword.com/environment: "dev-lab"
---
# Dev Lab Environment Secrets Management Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grill-stats-secrets-manager-dev
  namespace: grill-stats-dev
  labels:
    app: grill-stats
    component: secrets
    environment: dev-lab
    managed-by: onepassword-connect
rules:
# Secret management (dev environment)
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# OnePassword Connect resources (dev environment)
- apiGroups: ["onepassword.com"]
  resources: ["onepassworditems"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# ConfigMap access for configuration
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# Events for auditing
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
# Additional permissions for dev environment
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
# Dev Lab Environment Secrets Management RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grill-stats-secrets-manager-dev
  namespace: grill-stats-dev
  labels:
    app: grill-stats
    component: secrets
    environment: dev-lab
    managed-by: onepassword-connect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grill-stats-secrets-manager-dev
subjects:
- kind: ServiceAccount
  name: grill-stats-secrets-manager-dev
  namespace: grill-stats-dev
---
# Dev Lab Service Secrets Access Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grill-stats-services-secrets-dev
  namespace: grill-stats-dev
  labels:
    app: grill-stats
    component: services
    environment: dev-lab
    managed-by: onepassword-connect
  annotations:
    onepassword.com/service-account: "true"
    onepassword.com/environment: "dev-lab"
---
# Dev Lab Service Secrets Access Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grill-stats-services-secrets-dev
  namespace: grill-stats-dev
  labels:
    app: grill-stats
    component: services
    environment: dev-lab
    managed-by: onepassword-connect
rules:
# All service secrets in dev environment
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: 
    - "dev-lab-environment-secrets"
    - "dev-lab-database-users"
    - "auth-service-secrets"
    - "device-service-secrets"
    - "temperature-service-secrets"
    - "historical-data-service-secrets"
    - "encryption-service-secrets"
    - "web-ui-secrets"
    - "postgresql-secrets"
    - "influxdb-secrets"
    - "redis-secrets"
    - "timescaledb-secrets"
  verbs: ["get", "list", "watch"]
# OnePassword Connect resources for all services in dev
- apiGroups: ["onepassword.com"]
  resources: ["onepassworditems"]
  resourceNames:
    - "dev-lab-environment-secrets-1password"
    - "dev-lab-database-users-1password"
    - "auth-service-secrets-1password"
    - "device-service-secrets-1password"
    - "temperature-service-secrets-1password"
    - "historical-data-service-secrets-1password"
    - "encryption-service-secrets-1password"
    - "web-ui-secrets-1password"
  verbs: ["get", "list", "watch"]
---
# Dev Lab Service Secrets Access RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grill-stats-services-secrets-dev
  namespace: grill-stats-dev
  labels:
    app: grill-stats
    component: services
    environment: dev-lab
    managed-by: onepassword-connect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grill-stats-services-secrets-dev
subjects:
- kind: ServiceAccount
  name: grill-stats-services-secrets-dev
  namespace: grill-stats-dev
---
# Dev Lab Database Access Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grill-stats-database-secrets-dev
  namespace: grill-stats-dev
  labels:
    app: grill-stats
    component: database
    environment: dev-lab
    managed-by: onepassword-connect
---
# Dev Lab Database Access Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grill-stats-database-secrets-dev
  namespace: grill-stats-dev
  labels:
    app: grill-stats
    component: database
    environment: dev-lab
    managed-by: onepassword-connect
rules:
# Database-related secrets only
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: 
    - "dev-lab-database-users"
    - "postgresql-secrets"
    - "influxdb-secrets"
    - "redis-secrets"
    - "timescaledb-secrets"
  verbs: ["get", "list", "watch"]
# OnePassword Connect resources for database secrets
- apiGroups: ["onepassword.com"]
  resources: ["onepassworditems"]
  resourceNames:
    - "dev-lab-database-users-1password"
    - "postgresql-secrets-1password"
    - "influxdb-secrets-1password"
    - "redis-secrets-1password"
    - "timescaledb-secrets-1password"
  verbs: ["get", "list", "watch"]
---
# Dev Lab Database Access RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grill-stats-database-secrets-dev
  namespace: grill-stats-dev
  labels:
    app: grill-stats
    component: database
    environment: dev-lab
    managed-by: onepassword-connect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grill-stats-database-secrets-dev
subjects:
- kind: ServiceAccount
  name: grill-stats-database-secrets-dev
  namespace: grill-stats-dev