---
# 1Password Connect configuration for Vault token management
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vault-token-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: security
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/HomeLab/items/grill-stats-vault-token"
  secretName: vault-token-secret
  secretKey: token
---
# Secret for Vault token (populated by 1Password Connect)
apiVersion: v1
kind: Secret
metadata:
  name: vault-token-secret
  namespace: grill-stats
  labels:
    app: grill-stats
    component: security
    managed-by: onepassword-connect
type: Opaque
data: {}  # Will be populated by 1Password Connect
---
# 1Password Connect configuration for Vault admin token
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vault-admin-token-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: security
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/HomeLab/items/grill-stats-vault-admin-token"
  secretName: vault-admin-token-secret
  secretKey: token
---
# Secret for Vault admin token (for key rotation)
apiVersion: v1
kind: Secret
metadata:
  name: vault-admin-token-secret
  namespace: grill-stats
  labels:
    app: grill-stats
    component: security
    managed-by: onepassword-connect
type: Opaque
data: {}  # Will be populated by 1Password Connect
---
# 1Password Connect configuration for database credentials
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: database-credentials-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: security
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/HomeLab/items/grill-stats-database-credentials"
  secretName: database-credentials-secret
---
# Secret for database credentials
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials-secret
  namespace: grill-stats
  labels:
    app: grill-stats
    component: security
    managed-by: onepassword-connect
type: Opaque
data: {}  # Will be populated by 1Password Connect
---
# 1Password Connect configuration for JWT secrets
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: jwt-secrets-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: security
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/HomeLab/items/grill-stats-jwt-secrets"
  secretName: jwt-secrets-secret
---
# Secret for JWT secrets
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets-secret
  namespace: grill-stats
  labels:
    app: grill-stats
    component: security
    managed-by: onepassword-connect
type: Opaque
data: {}  # Will be populated by 1Password Connect
---
# 1Password Connect configuration for ThermoWorks API credentials
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: thermoworks-api-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: security
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/HomeLab/items/grill-stats-thermoworks-api"
  secretName: thermoworks-api-secret
---
# Secret for ThermoWorks API credentials
apiVersion: v1
kind: Secret
metadata:
  name: thermoworks-api-secret
  namespace: grill-stats
  labels:
    app: grill-stats
    component: security
    managed-by: onepassword-connect
type: Opaque
data: {}  # Will be populated by 1Password Connect