apiVersion: v1
kind: ConfigMap
metadata:
  name: grill-stats-config
  namespace: grill-stats
data:
  SYNC_INTERVAL: "300"
  TEMPERATURE_THRESHOLD_HIGH: "250"
  TEMPERATURE_THRESHOLD_LOW: "32"
  DB_HOST: "postgresql-service"
  REDIS_HOST: "redis-service"
  INFLUXDB_HOST: "influxdb-service"
