apiVersion: v1
kind: ResourceQuota
metadata:
  name: grill-monitoring-quota
  namespace: grill-monitoring
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "30"
    services: "15"
    services.loadbalancers: "2"