apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vault-token-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: security
spec:
  itemPath: "vaults/HomeLab/items/grill-stats-vault-token"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: security
type: Opaque
stringData:
  token: ""  # Will be populated by 1Password Connect
  vault_addr: "https://vault.vault.svc.cluster.local:8200"
  transit_path: "transit"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: encryption-service-config-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: security
spec:
  itemPath: "vaults/HomeLab/items/grill-stats-encryption-config"
---
apiVersion: v1
kind: Secret
metadata:
  name: encryption-service-config-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: security
type: Opaque
stringData:
  encryption_config: ""  # Will be populated by 1Password Connect
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vault-root-token-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: security
spec:
  itemPath: "vaults/HomeLab/items/vault-root-token"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-root-token
  namespace: grill-stats
  labels:
    app: grill-stats
    component: security
type: Opaque
stringData:
  token: ""  # Will be populated by 1Password Connect
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vault-kubernetes-ca-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: security
spec:
  itemPath: "vaults/HomeLab/items/vault-kubernetes-ca-cert"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-kubernetes-ca
  namespace: grill-stats
  labels:
    app: grill-stats
    component: security
type: Opaque
stringData:
  ca.crt: ""  # Will be populated by 1Password Connect
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vault-tls-cert-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: security
spec:
  itemPath: "vaults/HomeLab/items/vault-tls-certificate"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-tls-cert
  namespace: grill-stats
  labels:
    app: grill-stats
    component: security
type: kubernetes.io/tls
stringData:
  tls.crt: ""  # Will be populated by 1Password Connect
  tls.key: ""  # Will be populated by 1Password Connect