apiVersion: v1
kind: Secret
metadata:
  name: grill-stats-secrets
  namespace: ${NAMESPACE}
  labels:
    app: grill-stats
    environment: ${ENVIRONMENT}
type: Opaque
data:
  thermoworks-api-key: ${THERMOWORKS_API_KEY_BASE64}
  thermoworks-client-id: ${THERMOWORKS_CLIENT_ID_BASE64}
  thermoworks-client-secret: ${THERMOWORKS_CLIENT_SECRET_BASE64}
  homeassistant-token: ${HOMEASSISTANT_TOKEN_BASE64}
  secret-key: ${SECRET_KEY_BASE64}
  jwt-secret: ${JWT_SECRET_BASE64}
