apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secrets
  namespace: ${NAMESPACE}
  labels:
    app: influxdb
    environment: ${ENVIRONMENT}
type: Opaque
data:
  username: ${INFLUXDB_USERNAME_BASE64}
  password: ${INFLUXDB_PASSWORD_BASE64}
