apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: ${NAMESPACE}
  labels:
    app: postgres
    environment: ${ENVIRONMENT}
type: Opaque
data:
  username: ${DB_USER_BASE64}
  password: ${DB_PASSWORD_BASE64}
