apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-operator
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: backup-operator
    app.kubernetes.io/component: backup
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-operator
  namespace: grill-stats
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backup-operator
  namespace: grill-stats
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backup-operator
subjects:
- kind: ServiceAccount
  name: backup-operator
  namespace: grill-stats

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-restore
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: backup-restore
    app.kubernetes.io/component: backup
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-restore
  namespace: grill-stats
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: [""]
  resources: ["pods/attach"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backup-restore
  namespace: grill-stats
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backup-restore
subjects:
- kind: ServiceAccount
  name: backup-restore
  namespace: grill-stats