# Backup Encryption Key Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backup-encryption-secret
  namespace: grill-stats
spec:
  secretStoreRef:
    name: 1password-secret-store
    kind: SecretStore
  target:
    name: backup-encryption-secret
    creationPolicy: Owner
  data:
    - secretKey: encryption-key
      remoteRef:
        key: backup-encryption-key
        property: key
    - secretKey: s3-access-key
      remoteRef:
        key: backup-s3-credentials
        property: access-key
    - secretKey: s3-secret-key
      remoteRef:
        key: backup-s3-credentials
        property: secret-key
    - secretKey: restic-password
      remoteRef:
        key: backup-restic-password
        property: password

---
# Notification Webhook Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backup-notification-secret
  namespace: grill-stats
spec:
  secretStoreRef:
    name: 1password-secret-store
    kind: SecretStore
  target:
    name: backup-notification-secret
    creationPolicy: Owner
  data:
    - secretKey: webhook-url
      remoteRef:
        key: backup-webhook-url
        property: url
    - secretKey: slack-token
      remoteRef:
        key: backup-slack-token
        property: token
    - secretKey: email-password
      remoteRef:
        key: backup-email-credentials
        property: password

---
# Database Connection Secrets (Reference existing)
apiVersion: v1
kind: Secret
metadata:
  name: backup-db-connections
  namespace: grill-stats
type: Opaque
stringData:
  postgresql-connection: |
    host=grill-stats-db
    port=5432
    dbname=grill_stats
    user=grill_stats
    password_file=/secrets/postgresql/password
  influxdb-connection: |
    host=http://influxdb:8086
    org=grill-stats
    token_file=/secrets/influxdb/admin-token
  redis-connection: |
    host=redis
    port=6379
    password_file=/secrets/redis/password

---
# Simplified secrets for testing without 1Password
apiVersion: v1
kind: Secret
metadata:
  name: backup-encryption-secret
  namespace: grill-stats
type: Opaque
stringData:
  encryption-key: "backup-encryption-key-placeholder"
  s3-access-key: "access-key-placeholder"
  s3-secret-key: "secret-key-placeholder"
  restic-password: "restic-password-placeholder"

---
apiVersion: v1
kind: Secret
metadata:
  name: backup-notification-secret
  namespace: grill-stats
type: Opaque
stringData:
  webhook-url: "http://localhost:8080/webhook"
  slack-token: "slack-token-placeholder"
  email-password: "email-password-placeholder"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: grill-stats
type: Opaque
stringData:
  password: "backup-test-password"