apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/namespace

patchesStrategicMerge:
  - namespace.yaml
  - resourcequota.yaml
  - limitrange.yaml

commonLabels:
  environment: development

namespace: grill-stats-dev

namePrefix: dev-
