apiVersion: v1
kind: ResourceQuota
metadata:
  name: grill-stats-quota
  namespace: grill-stats-dev
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "30"
    services: "15"
    services.loadbalancers: "1"
    secrets: "20"
    configmaps: "20"
