apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processing-service
  namespace: grill-monitoring
  labels:
    app.kubernetes.io/name: data-processing-service
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: data-processing-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: data-processing-service
        app.kubernetes.io/part-of: grill-stats
        app.kubernetes.io/component: microservice
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: data-processing-service
        image: grill-stats/data-processing-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: INFLUXDB_HOST
          valueFrom:
            configMapKeyRef:
              name: grill-monitoring-config
              key: INFLUXDB_HOST
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: grill-monitoring-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grill-monitoring-secrets
              key: DB_PASSWORD
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: OTEL_SERVICE_NAME
          value: data-processing-service
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4317"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: data-processing-service
  namespace: grill-monitoring
  labels:
    app.kubernetes.io/name: data-processing-service
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: microservice
spec:
  selector:
    app.kubernetes.io/name: data-processing-service
  ports:
  - port: 8080
    targetPort: http
    name: http
  type: ClusterIP