apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: notification-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: notification-service
        app.kubernetes.io/part-of: grill-stats
        app.kubernetes.io/component: microservice
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: notification-service
        image: lordmuffin/grill-stats-notification-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: grill-stats-config
              key: REDIS_HOST
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grill-stats-secrets
              key: REDIS_PASSWORD
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: TEMPERATURE_THRESHOLD_HIGH
          valueFrom:
            configMapKeyRef:
              name: grill-stats-config
              key: TEMPERATURE_THRESHOLD_HIGH
        - name: TEMPERATURE_THRESHOLD_LOW
          valueFrom:
            configMapKeyRef:
              name: grill-stats-config
              key: TEMPERATURE_THRESHOLD_LOW
        - name: OTEL_SERVICE_NAME
          value: notification-service
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4317"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: microservice
spec:
  selector:
    app.kubernetes.io/name: notification-service
  ports:
  - port: 8080
    targetPort: http
    name: http
  type: ClusterIP
