apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-deny-all.yaml
  - allow-ingress-from-traefik.yaml
  - allow-dns-access.yaml
  - allow-database-access.yaml
  - allow-service-mesh.yaml
  - allow-external-api.yaml
  - allow-vault-access.yaml
  - allow-monitoring.yaml
  - allow-kafka-access.yaml
  - allow-homeassistant-access.yaml
  - allow-thermoworks-api-access.yaml

commonLabels:
  app.kubernetes.io/name: grill-stats
  app.kubernetes.io/part-of: grill-stats
  app.kubernetes.io/managed-by: kustomize

namespace: grill-stats
