apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grill-stats
  namespace: grill-stats-dev
spec:
  tls:
  - hosts:
    - grills-dev.lab.apj.dev
    secretName: grill-stats-tls
  rules:
  - host: grills-dev.lab.apj.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grill-stats
            port:
              number: 80