apiVersion: apps/v1
kind: Deployment
metadata:
  name: grill-stats
  namespace: grill-monitoring-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: grill-stats
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"