name: Alert Service Build

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
    paths:
      - 'services/alert-service/**'
      - '.gitea/workflows/alert-service-build.yml'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: docker.io
      IMAGE_NAME: lordmuffin/grill-stats-alert-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies and Lint
        run: |
          # Install packages
          python -m pip install --upgrade pip
          if [ -f services/alert-service/requirements.txt ]; then
            pip install -r services/alert-service/requirements.txt
          else
            echo "No requirements.txt found"
          fi

          # Install and run flake8
          pip install flake8
          flake8 services/alert-service --count --select=E9,F63,F7,F82 --show-source --statistics || true
          flake8 services/alert-service --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Setup Kaniko
        run: |
          echo "Setting up Kaniko executor..."

          # Download Kaniko executor
          curl -L https://github.com/google/go-containerregistry/releases/latest/download/go-containerregistry_Linux_x86_64.tar.gz | tar -xzf - -C /tmp/ crane
          /tmp/crane export gcr.io/kaniko-project/executor:v1.23.2 - | tar -xf - -C /tmp/ kaniko/executor
          cp /tmp/kaniko/executor /tmp/executor
          chmod +x /tmp/executor

          # Test Docker Hub connectivity
          echo "Testing Docker Hub connectivity..."
          curl -s https://index.docker.io/v1/ || echo "Docker Hub connectivity test completed"

      - name: Build and Push with Kaniko to Local, then Crane
        run: |
          # Generate semantic version tags
          VERSION=$(cat VERSION)
          SHORT_SHA=$(git rev-parse --short HEAD)
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          # Determine version tags based on branch and context
          if [ "$BRANCH_NAME" = "main" ]; then
            # Main branch: use semantic version + latest
            MAIN_TAG="$VERSION"
            LATEST_TAG="latest"
            echo "Building PRODUCTION release: v$VERSION"
          elif [ "$BRANCH_NAME" = "develop" ]; then
            # Develop branch: use version + dev suffix
            MAIN_TAG="$VERSION-dev"
            LATEST_TAG="dev"
            echo "Building DEVELOPMENT release: v$VERSION-dev"
          else
            # Feature/other branches: use version + branch + sha
            SAFE_BRANCH=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9._-]/-/g')
            MAIN_TAG="$VERSION-$SAFE_BRANCH-$SHORT_SHA"
            LATEST_TAG="$SAFE_BRANCH"
            echo "Building FEATURE branch release: v$VERSION-$SAFE_BRANCH-$SHORT_SHA"
          fi

          # Debug: Check environment
          echo "Registry: ${{ env.DOCKER_REGISTRY }}"
          echo "Base Image: ${{ env.IMAGE_NAME }}"
          echo "Version: $VERSION"
          echo "Branch: $BRANCH_NAME"
          echo "Short SHA: $SHORT_SHA"
          echo "Build Date: $BUILD_DATE"
          echo "Main Tag: $MAIN_TAG"
          echo "Latest Tag: $LATEST_TAG"

          # Build with Kaniko to local tar file (no registry push)
          echo "Building container image to local tar..."

          # Create tar context for alert service
          tar -czf /tmp/context.tar.gz --exclude='.git' --exclude='.gitea' -C services/alert-service .

          # Run Kaniko to build and export to tar (no push)
          /tmp/executor \
            --context=tar:///tmp/context.tar.gz \
            --tarPath=/tmp/image.tar \
            --no-push \
            --custom-platform=linux/amd64 \
            --single-snapshot

          # Use crane to push the tar to registry with explicit auth
          echo "Pushing with crane..."

          # Create Docker config for crane
          mkdir -p ~/.docker
          echo "Setting up Docker Hub authentication..."

          # Use Docker Hub credentials (hardcoded for testing, will use secrets later)
          AUTH_STRING="bG9yZG11ZmZpbjpkY2tyX3BhdF9nSWJScjBsRnZ6LTlxMFFZVDVKc01FQ0p5VDQ="
          echo "Docker Hub auth configured with valid credentials"

          cat > ~/.docker/config.json << EOF
          {
            "auths": {
              "https://index.docker.io/v1/": {
                "auth": "${AUTH_STRING}"
              }
            }
          }
          EOF

          # Test the tar file first
          echo "Testing tar file:"
          ls -la /tmp/image.tar

          # Push to Docker Hub with crane
          echo "Attempting push to Docker Hub with crane..."
          echo "Target image: ${{ env.IMAGE_NAME }}:latest"
          echo "Testing crane version..."
          /tmp/crane version || echo "Crane version check failed"
          echo "Docker config contents:"
          cat ~/.docker/config.json

          echo "Pushing to Docker Hub with semantic versioning..."

          # Push main semantic version tag
          echo "Pushing main tag: ${{ env.IMAGE_NAME }}:$MAIN_TAG"
          if /tmp/crane push /tmp/image.tar ${{ env.IMAGE_NAME }}:$MAIN_TAG \
            --platform=linux/amd64; then
            echo "✅ Main tag push succeeded: $MAIN_TAG"
          else
            echo "❌ Main tag push failed: $MAIN_TAG"
            exit 1
          fi

          # Push latest/dev/branch tag
          echo "Pushing latest tag: ${{ env.IMAGE_NAME }}:$LATEST_TAG"
          if /tmp/crane push /tmp/image.tar ${{ env.IMAGE_NAME }}:$LATEST_TAG \
            --platform=linux/amd64; then
            echo "✅ Latest tag push succeeded: $LATEST_TAG"
          else
            echo "❌ Latest tag push failed: $LATEST_TAG"
            exit 1
          fi

          # For main branch, also push with 'v' prefix (e.g., v1.0.0)
          if [ "$BRANCH_NAME" = "main" ]; then
            echo "Pushing version tag: ${{ env.IMAGE_NAME }}:v$VERSION"
            if /tmp/crane push /tmp/image.tar ${{ env.IMAGE_NAME }}:v$VERSION \
              --platform=linux/amd64; then
              echo "✅ Version tag push succeeded: v$VERSION"
            else
              echo "❌ Version tag push failed: v$VERSION"
              exit 1
            fi
          fi

          echo "🎉 All tags pushed successfully to Docker Hub!"
          echo "📦 Available tags:"
          echo "   - ${{ env.IMAGE_NAME }}:$MAIN_TAG"
          echo "   - ${{ env.IMAGE_NAME }}:$LATEST_TAG"
          if [ "$BRANCH_NAME" = "main" ]; then
            echo "   - ${{ env.IMAGE_NAME }}:v$VERSION"
          fi
