name: Build and Test Grill Stats

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies and Lint
        container:
          image: python:3.11-slim
        run: |
          # 1. Create a virtual environment in the shared workspace
          python -m venv /workspace/venv
          
          # 2. Activate the virtual environment for subsequent commands
          . /workspace/venv/bin/activate
          
          # 3. Install packages into the isolated venv
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found"
          fi
          
          # 4. Install and run flake8 from within the venv
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build:
    needs: test
    runs-on: ubuntu-latest
    env:
      GITEA_REGISTRY: gitea-http.gitea.svc.cluster.local:3000
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Kaniko Config
        run: |
          mkdir -p /workspace/kaniko-config
          echo '{"auths":{"${{ env.GITEA_REGISTRY }}":{"username":"${{ secrets.REGISTRY_USERNAME }}","password":"${{ secrets.REGISTRY_PASSWORD }}"}},"http-insecure-registries":["${{ env.GITEA_REGISTRY }}"]}' > /workspace/kaniko-config/config.json
          echo "Kaniko config created successfully."

      # FIX: Reverted to the 'uses:' syntax, which is the most robust way to
      # invoke a container action and avoids PATH issues on the runner.
      - name: Build and Push with Kaniko
        uses: docker://gcr.io/kaniko-project/executor:debug
        with:
          args: |
            --docker-config-dir=/workspace/kaniko-config
            --context=/workspace
            --dockerfile=/workspace/Dockerfile
            --destination=${{ env.GITEA_REGISTRY }}/lordmuffin/grill-stats:latest
            --customPlatform=linux/amd64
