name: Build and Test Grill Stats

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # FIX: Removed explicit 'repository' and 'ref' to let the action
      # automatically check out the commit that triggered the workflow.
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        container:
          image: python:3.11-slim
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found"
          fi

      - name: Lint with flake8
        container:
          image: python:3.11-slim
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # FIX: Also removed explicit 'repository' and 'ref' here for consistency.
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Push with Kaniko
        uses: docker://gcr.io/kaniko-project/executor:v1.9.0
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        with:
          args: |
            --context=dir:///workspace/
            --dockerfile=./Dockerfile
            --destination=gitea-internal/your-image-name:latest
            --custom-platform=linux/amd64
