name: Build and Test Grill Stats
run-name: ${{ gitea.actor }} triggered build for ${{ gitea.ref_name }}

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test application startup
        run: |
          # Test that the application can import without errors
          python -c "import app; print('✅ App imports successfully')"
          python -c "import thermoworks_client; print('✅ ThermoWorks client imports successfully')"
          python -c "import homeassistant_client; print('✅ Home Assistant client imports successfully')"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t grill-stats:${{ gitea.sha }} .
          docker build -t grill-stats:latest .

      - name: Test Docker image
        run: |
          # Test that the Docker image runs without immediate crash
          timeout 10s docker run --rm grill-stats:latest || [ $? -eq 124 ]
          echo "✅ Docker image builds and starts successfully"

      - name: Save Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker save grill-stats:latest | gzip > grill-stats-latest.tar.gz

      - name: Upload Docker image artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: grill-stats-latest.tar.gz
          retention-days: 7