name: Build and Test Grill Stats

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies and Lint
        container:
          image: python:3.11-slim
        run: |
          # 1. Create a virtual environment in the shared workspace
          python -m venv /workspace/venv
          
          # 2. Activate the virtual environment for subsequent commands
          . /workspace/venv/bin/activate
          
          # 3. Install packages into the isolated venv
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found"
          fi
          
          # 4. Install and run flake8 from within the venv
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build:
    needs: test
    runs-on: ubuntu-latest
    env:
      GITEA_REGISTRY: gitea-http.gitea.svc.cluster.local:3000
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Push with Kaniko
        uses: docker://gcr.io/kaniko-project/executor:v1.9.0
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        with:
          args: |
            --context=dir:///workspace
            --dockerfile=Dockerfile
            --destination=${{ env.GITEA_REGISTRY }}/lordmuffin/grill-stats:latest
            --customPlatform=linux/amd64
            --insecure-registry=${{ env.GITEA_REGISTRY }}
