name: Build and Test Grill Stats

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    container:
      image: python:3.11-slim
    steps:
      - name: Checkout code manually
        run: |
          # Prepare system
          mkdir -p /workspace
          cd /workspace
          
          # Debug information
          echo "Current directory: $(pwd)"
          ls -la
          
          # Install git quietly to avoid stderr noise
          apt-get update -qq > /dev/null 2>&1
          apt-get install -y -qq git > /dev/null 2>&1
          
          # If directory is not empty, use existing files
          if [ "$(ls -A)" ]; then
            echo "Using existing files in workspace"
          else
            # Only clone if directory is empty
            echo "Cloning repository..."
            git clone https://github.com/lordmuffin/grill-stats.git .
            git checkout main
          fi
          
          # Verify checkout
          echo "Repository contents:"
          ls -la
          echo "Checkout complete"

      # Python setup is not needed since we're using a Python container
      # This step is removed to avoid potential conflicts

      - name: Install dependencies
        run: |
          cd /workspace
          echo "Current directory: $(pwd)"
          ls -la
          python -m pip install --upgrade pip
          echo "Checking for requirements.txt"
          if [ -f requirements.txt ]; then
            echo "Installing from requirements.txt"
            pip install -r requirements.txt
          else
            echo "No requirements.txt found"
            find . -name "requirements.txt"
          fi

      - name: Lint with flake8
        run: |
          cd /workspace
          pip install flake8
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
          # Exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test application startup
        run: |
          # Test that the application can import without errors
          # python -c "import app; print('✅ App imports successfully')"
          # python -c "import thermoworks_client; print('✅ ThermoWorks client imports successfully')"
          # python -c "import homeassistant_client; print('✅ Home Assistant client imports successfully')"

  build:
      needs: test
      # REMOVE the job-level 'container:' block entirely.
      # The runner will use a default pod environment.
      steps:
        - name: Checkout Code
          # Use a standard image that includes git for this step
          uses: docker://alpine/git:latest
          run: |
            # The runner provides a shared /workspace for all steps
            git clone https://github.com/lordmuffin/grill-stats.git .
            git checkout main
            echo "--- Workspace Contents After Checkout ---"
            ls -la

        - name: Build and Push with Kaniko
          # NOW use the Kaniko image, only for this step
          uses: docker://gcr.io/kaniko-project/executor:v1.9.0
          env:
            # Pass secrets to the step as environment variables
            REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
            REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          run: |
            # 1. Create Kaniko's credential file from the secrets
            mkdir -p /kaniko/.docker
            echo '{"auths":{"gitea-internal":{"username":"'${REGISTRY_USERNAME}'","password":"'${REGISTRY_PASSWORD}'"}}}' > /kaniko/.docker/config.json

            # 2. Run the Kaniko executor
            # It builds from the /workspace populated by the checkout step
            # and pushes to the destination.
            /kaniko/executor \
              --context=/workspace \
              --dockerfile=/workspace/Dockerfile \
              --destination=gitea-internal/your-image-name:latest