name: Build and Test Grill Stats
# Pipeline bump: 2025-07-06T21:32:00Z - Force pipeline execution

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      GITEA_REGISTRY: gitea-internal.gitea.svc.cluster.local:80
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies and Lint
        run: |
          # Install packages
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found"
          fi
          
          # Install and run flake8
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Setup Kaniko
        run: |
          # Download a working version from a reliable source
          echo "Downloading Kaniko executor from container registry..."
          
          # Use crane or direct extraction from container
          # First try to install crane
          curl -L https://github.com/google/go-containerregistry/releases/latest/download/go-containerregistry_Linux_x86_64.tar.gz | tar -xzf - -C /tmp/ crane
          
          # Extract executor from the official Kaniko image
          /tmp/crane export gcr.io/kaniko-project/executor:v1.23.2 - | tar -xf - -C /tmp/ kaniko/executor
          
          # Move to expected location
          cp /tmp/kaniko/executor /tmp/executor
          chmod +x /tmp/executor
          
          # Verify the download
          file /tmp/executor
          
          # Create Docker config directory and test auth
          mkdir -p /tmp/docker-config
          
          # Debug: Check if registry is accessible
          echo "Testing registry connectivity..."
          echo "Testing HTTP endpoint:"
          curl -v http://${{ env.GITEA_REGISTRY }}/v2/ || echo "Registry API not accessible at HTTP /v2/"
          echo "Testing HTTPS endpoint:"
          curl -v https://${{ env.GITEA_REGISTRY }}/v2/ || echo "Registry API not accessible at HTTPS /v2/"
          echo "Testing base path:"
          curl -v http://${{ env.GITEA_REGISTRY }}/ || echo "Base path not accessible"
          
          # Create auth config - use only internal registry to bypass Traefik auth
          AUTH_STRING=$(echo -n "${{ secrets.REGISTRY_USERNAME }}:${{ secrets.REGISTRY_PASSWORD }}" | base64 -w 0)
          cat > /tmp/docker-config/config.json << EOF
          {
            "auths": {
              "${{ env.GITEA_REGISTRY }}": {
                "username": "${{ secrets.REGISTRY_USERNAME }}",
                "password": "${{ secrets.REGISTRY_PASSWORD }}",
                "auth": "${AUTH_STRING}"
              }
            },
            "HttpHeaders": {
              "User-Agent": "kaniko/executor"
            }
          }
          EOF
          
          # Debug: Show config (redacted)
          echo "Docker config created:"
          cat /tmp/docker-config/config.json | jq 'del(.auths[].password, .auths[].auth)'

      - name: Build and Push with Kaniko
        run: |
          # Debug: Check environment
          echo "Registry: ${{ env.GITEA_REGISTRY }}"
          echo "Destination: ${{ env.GITEA_REGISTRY }}/gitea-admin/grill-stats:latest"
          
          # Set Kaniko options for debugging
          export DOCKER_CONFIG=/tmp/docker-config
          
          # Run Kaniko with registry map to override token realm
          /tmp/executor \
            --context=${{ github.workspace }} \
            --dockerfile=${{ github.workspace }}/Dockerfile \
            --destination=${{ env.GITEA_REGISTRY }}/gitea-admin/grill-stats:latest \
            --custom-platform=linux/amd64 \
            --verbosity=debug \
            --insecure \
            --skip-tls-verify \
            --registry-map=git.lab.apj.dev=${{ env.GITEA_REGISTRY }}
