name: Secure Build and Test Pipeline
# Pipeline bump: 2025-07-19T14:30:00Z - Updated pipeline with comprehensive testing and secure secret management

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_REGISTRY: docker.io
  IMAGE_NAME: lordmuffin/grill-stats

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Use secrets for environment configuration
      THERMOWORKS_API_KEY: ${{ secrets.THERMOWORKS_API_KEY }}
      HOMEASSISTANT_URL: ${{ secrets.HOMEASSISTANT_URL }}
      HOMEASSISTANT_TOKEN: ${{ secrets.HOMEASSISTANT_TOKEN }}
      # Database configuration
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      # Application configuration
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      MOCK_MODE: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          # Install system dependencies including PostgreSQL development packages
          sudo apt-get update
          sudo apt-get install -y postgresql-client libpq-dev

      - name: Install Python Dependencies
        run: |
          # Install packages
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          # Install dev dependencies for linting
          pip install flake8 black isort mypy

      - name: Run Syntax Checks
        run: |
          # Critical errors - fail the build if these occur
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run Code Style Checks
        run: |
          # Style checks - report but don't fail the build
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          black --check --diff .
          isort --check --diff .

      - name: Run Type Checking
        run: |
          # Type checking - exit-zero for now as we implement gradually
          mypy --install-types --non-interactive --ignore-missing-imports app.py thermoworks_client.py homeassistant_client.py || echo "Type checking completed with issues"

      - name: Setup Test Environment
        run: |
          # Create .env file with test configuration
          cat > .env << EOF
          MOCK_MODE=true
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          THERMOWORKS_API_KEY=${{ secrets.THERMOWORKS_API_KEY }}
          HOMEASSISTANT_URL=${{ secrets.HOMEASSISTANT_URL }}
          HOMEASSISTANT_TOKEN=${{ secrets.HOMEASSISTANT_TOKEN }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          EOF

      - name: Run Unit Tests
        run: |
          # Run pytest on the unit tests
          python -m pytest tests/unit -v

      - name: Run Alert System Tests
        run: |
          # Run the alert system tests
          python test_alert_system.py

  build:
    runs-on: ubuntu-latest
    needs: test
    env:
      DOCKER_REGISTRY: ${{ env.DOCKER_REGISTRY }}
      IMAGE_NAME: ${{ env.IMAGE_NAME }}
      # Use secure Docker Hub credentials from repository secrets
      DOCKER_AUTH: ${{ secrets.DOCKER_AUTH }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          # Install system dependencies including PostgreSQL development packages
          sudo apt-get update
          sudo apt-get install -y postgresql-client libpq-dev

      - name: Install Python Dependencies
        run: |
          # Install packages
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found"
          fi

      - name: Run Vulnerability Scanning
        run: |
          # Install safety for Python package vulnerability scanning
          pip install safety
          safety check -r requirements.txt || echo "Vulnerability check completed with findings"

      - name: Setup Kaniko
        run: |
          # Setup Kaniko executor
          echo "Setting up Kaniko executor..."

          # Download Kaniko executor
          curl -L https://github.com/google/go-containerregistry/releases/latest/download/go-containerregistry_Linux_x86_64.tar.gz | tar -xzf - -C /tmp/ crane
          /tmp/crane export gcr.io/kaniko-project/executor:v1.23.2 - | tar -xf - -C /tmp/ kaniko/executor
          cp /tmp/kaniko/executor /tmp/executor
          chmod +x /tmp/executor

          # Test Docker Hub connectivity
          echo "Testing Docker Hub connectivity..."
          curl -s https://index.docker.io/v1/ || echo "Docker Hub connectivity test completed"

      - name: Build and Push with Kaniko to Local, then Crane
        env:
          # Use secure repository secrets
          DOCKER_AUTH: ${{ secrets.DOCKER_AUTH }}
          # Application secrets for build-time configuration
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          THERMOWORKS_API_KEY: ${{ secrets.THERMOWORKS_API_KEY }}
        run: |
          # Generate semantic version tags
          VERSION=$(cat VERSION)
          SHORT_SHA=$(git rev-parse --short HEAD)
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          # Determine version tags based on branch and context
          if [ "$BRANCH_NAME" = "main" ]; then
            # Main branch: use semantic version + latest
            MAIN_TAG="$VERSION"
            LATEST_TAG="latest"
            echo "Building PRODUCTION release: v$VERSION"
          elif [ "$BRANCH_NAME" = "develop" ]; then
            # Develop branch: use version + dev suffix
            MAIN_TAG="$VERSION-dev"
            LATEST_TAG="dev"
            echo "Building DEVELOPMENT release: v$VERSION-dev"
          else
            # Feature/other branches: use version + branch + sha
            SAFE_BRANCH=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9._-]/-/g')
            MAIN_TAG="$VERSION-$SAFE_BRANCH-$SHORT_SHA"
            LATEST_TAG="$SAFE_BRANCH"
            echo "Building FEATURE branch release: v$VERSION-$SAFE_BRANCH-$SHORT_SHA"
          fi

          # Debug: Check environment
          echo "Registry: ${{ env.DOCKER_REGISTRY }}"
          echo "Base Image: ${{ env.IMAGE_NAME }}"
          echo "Version: $VERSION"
          echo "Branch: $BRANCH_NAME"
          echo "Short SHA: $SHORT_SHA"
          echo "Build Date: $BUILD_DATE"
          echo "Main Tag: $MAIN_TAG"
          echo "Latest Tag: $LATEST_TAG"

          # Create secure build args file
          cat > /tmp/build-args.env << EOF
          SECRET_KEY=$SECRET_KEY
          MOCK_MODE=true
          EOF

          # Build with Kaniko to local tar file (no registry push)
          echo "Building container image to local tar..."

          # Create tar context
          tar -czf /tmp/context.tar.gz --exclude='.git' --exclude='.gitea' .

          # Run Kaniko to build and export to tar (no push)
          /tmp/executor \
            --context=tar:///tmp/context.tar.gz \
            --tarPath=/tmp/image.tar \
            --no-push \
            --env-file=/tmp/build-args.env \
            --custom-platform=linux/amd64 \
            --single-snapshot

          # Use crane to push the tar to registry with explicit auth
          echo "Pushing with crane..."

          # Create Docker config for crane
          mkdir -p ~/.docker
          echo "Setting up Docker Hub authentication..."

          # Check if Docker auth is available
          if [ -z "$DOCKER_AUTH" ]; then
            echo "❌ ERROR: DOCKER_AUTH secret is not set"
            echo "Please configure the DOCKER_AUTH secret in your repository settings"
            echo "Format should be: username:password or username:token encoded in base64"
            exit 1
          fi

          # Use Docker Hub credentials from secrets
          cat > ~/.docker/config.json << EOF
          {
            "auths": {
              "https://index.docker.io/v1/": {
                "auth": "${DOCKER_AUTH}"
              }
            }
          }
          EOF

          echo "Docker Hub auth configured with secure credentials"

          # Test the tar file first
          echo "Testing tar file:"
          ls -la /tmp/image.tar

          # Push to Docker Hub with crane
          echo "Attempting push to Docker Hub with crane..."
          echo "Target image: ${{ env.IMAGE_NAME }}:latest"

          # Push main semantic version tag
          echo "Pushing main tag: ${{ env.IMAGE_NAME }}:$MAIN_TAG"
          if /tmp/crane push /tmp/image.tar ${{ env.IMAGE_NAME }}:$MAIN_TAG \
            --platform=linux/amd64; then
            echo "✅ Main tag push succeeded: $MAIN_TAG"
          else
            echo "❌ Main tag push failed: $MAIN_TAG"
            exit 1
          fi

          # Push latest/dev/branch tag
          echo "Pushing latest tag: ${{ env.IMAGE_NAME }}:$LATEST_TAG"
          if /tmp/crane push /tmp/image.tar ${{ env.IMAGE_NAME }}:$LATEST_TAG \
            --platform=linux/amd64; then
            echo "✅ Latest tag push succeeded: $LATEST_TAG"
          else
            echo "❌ Latest tag push failed: $LATEST_TAG"
            exit 1
          fi

          # For main branch, also push with 'v' prefix (e.g., v1.0.0)
          if [ "$BRANCH_NAME" = "main" ]; then
            echo "Pushing version tag: ${{ env.IMAGE_NAME }}:v$VERSION"
            if /tmp/crane push /tmp/image.tar ${{ env.IMAGE_NAME }}:v$VERSION \
              --platform=linux/amd64; then
              echo "✅ Version tag push succeeded: v$VERSION"
            else
              echo "❌ Version tag push failed: v$VERSION"
              exit 1
            fi
          fi

          echo "🎉 All tags pushed successfully to Docker Hub!"
          echo "📦 Available tags:"
          echo "   - ${{ env.IMAGE_NAME }}:$MAIN_TAG"
          echo "   - ${{ env.IMAGE_NAME }}:$LATEST_TAG"
          if [ "$BRANCH_NAME" = "main" ]; then
            echo "   - ${{ env.IMAGE_NAME }}:v$VERSION"
          fi

      - name: Scan Docker Image for Vulnerabilities
        run: |
          # Install trivy scanner
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

          # Scan the built image
          trivy image --input /tmp/image.tar || echo "Image vulnerability scan completed with findings"

      - name: Verify Container Startup
        env:
          # Use repository secrets for container verification
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          # Load the image into local Docker
          podman load -i /tmp/image.tar

          # Run the container and verify it starts correctly
          CONTAINER_ID=$(podman run -d --name grill-stats-test -e MOCK_MODE=true -e SECRET_KEY=$SECRET_KEY ${{ env.IMAGE_NAME }}:$LATEST_TAG)

          # Wait for container to start
          sleep 10

          # Check container status
          if podman inspect $CONTAINER_ID --format '{{.State.Status}}' | grep -q "running"; then
            echo "✅ Container started successfully"
          else
            echo "❌ Container failed to start"
            podman logs $CONTAINER_ID
            exit 1
          fi

          # Clean up
          podman stop $CONTAINER_ID
          podman rm $CONTAINER_ID

  # New job for environment-specific testing
  integration-test:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    env:
      # Use all required secrets for integration testing
      THERMOWORKS_API_KEY: ${{ secrets.THERMOWORKS_API_KEY }}
      HOMEASSISTANT_URL: ${{ secrets.HOMEASSISTANT_URL }}
      HOMEASSISTANT_TOKEN: ${{ secrets.HOMEASSISTANT_TOKEN }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      INFLUXDB_HOST: ${{ secrets.INFLUXDB_HOST }}
      INFLUXDB_PORT: ${{ secrets.INFLUXDB_PORT }}
      INFLUXDB_DATABASE: ${{ secrets.INFLUXDB_DATABASE }}
      INFLUXDB_USERNAME: ${{ secrets.INFLUXDB_USERNAME }}
      INFLUXDB_PASSWORD: ${{ secrets.INFLUXDB_PASSWORD }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      MOCK_MODE: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Setup Test Environment
        run: |
          # Create .env file with integration test configuration
          cat > .env << EOF
          MOCK_MODE=true
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          THERMOWORKS_API_KEY=${{ secrets.THERMOWORKS_API_KEY }}
          HOMEASSISTANT_URL=${{ secrets.HOMEASSISTANT_URL }}
          HOMEASSISTANT_TOKEN=${{ secrets.HOMEASSISTANT_TOKEN }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          INFLUXDB_HOST=${{ secrets.INFLUXDB_HOST }}
          INFLUXDB_PORT=${{ secrets.INFLUXDB_PORT }}
          INFLUXDB_DATABASE=${{ secrets.INFLUXDB_DATABASE }}
          INFLUXDB_USERNAME=${{ secrets.INFLUXDB_USERNAME }}
          INFLUXDB_PASSWORD=${{ secrets.INFLUXDB_PASSWORD }}
          REDIS_HOST=${{ secrets.REDIS_HOST }}
          REDIS_PORT=${{ secrets.REDIS_PORT }}
          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
          EOF

      - name: Run Integration Tests
        run: |
          # Run integration tests
          python -m pytest tests/integration -v || echo "Integration tests completed with issues"

      - name: Run Contract Tests
        run: |
          # Run contract tests
          python -m pytest tests/contract -v || echo "Contract tests completed with issues"

  # New job for security scanning
  security-scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Security Tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety
          sudo apt-get update
          sudo apt-get install -y git

      - name: Run Bandit Security Scan
        run: |
          bandit -r . -f json -o bandit-results.json || echo "Bandit scan completed with issues"

      - name: Run Safety Dependency Scan
        run: |
          safety check -r requirements.txt --json > safety-results.json || echo "Safety scan completed with issues"

      - name: Generate Security Report
        run: |
          echo "# Security Scan Results" > security-report.md
          echo "" >> security-report.md
          echo "## Bandit Results" >> security-report.md
          echo "" >> security-report.md
          echo "\`\`\`" >> security-report.md
          cat bandit-results.json | jq -r '.' >> security-report.md
          echo "\`\`\`" >> security-report.md
          echo "" >> security-report.md
          echo "## Safety Results" >> security-report.md
          echo "" >> security-report.md
          echo "\`\`\`" >> security-report.md
          cat safety-results.json | jq -r '.' >> security-report.md
          echo "\`\`\`" >> security-report.md

          echo "Security scanning completed. See security-report.md for details."

