name: Temperature Service Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths:
      - 'services/temperature-service/**'
      - '.gitea/workflows/temperature-service-build.yml'

jobs:
  build:
  
    
    container:
      image: gcr.io/kaniko-project/executor:v1.9.0-debug

      env:
        HOME: /kaniko

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Kaniko configuration
        run: |
          mkdir -p /kaniko/.docker
          echo '{"auths":{"gitea.lab.apj.dev":{"username":"${{ secrets.REGISTRY_USERNAME }}","password":"${{ secrets.REGISTRY_PASSWORD }}"}}}' > /kaniko/.docker/config.json

      - name: Get image tags
        id: tags
        run: |
          TAG=""
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            echo "TAG=${TAG}" >> $GITHUB_ENV
            echo "ADDITIONAL_TAG=latest" >> $GITHUB_ENV
          elif [[ "$GITHUB_REF" == refs/heads/main ]]; then
            TAG=main
            COMMIT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)
            echo "TAG=${TAG}" >> $GITHUB_ENV
            echo "ADDITIONAL_TAG=sha-${COMMIT_SHA}" >> $GITHUB_ENV
          else
            TAG=${GITHUB_REF#refs/heads/}
            COMMIT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)
            echo "TAG=${TAG}" >> $GITHUB_ENV
            echo "ADDITIONAL_TAG=sha-${COMMIT_SHA}" >> $GITHUB_ENV
          fi

      - name: Build and push with Kaniko
        run: |
          /kaniko/executor \
            --context="${PWD}/services/temperature-service" \
            --destination="gitea.lab.apj.dev/lordmuffin/grill-stats-temperature-service:${TAG}" \
            --destination="gitea.lab.apj.dev/lordmuffin/grill-stats-temperature-service:${ADDITIONAL_TAG}" \
            --cache=true \
            --cache-ttl=168h