apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
    component: backend
    tier: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        component: backend
        tier: auth
    spec:
      containers:
      - name: auth-service
        image: grill-stats/auth-service:latest
        ports:
        - containerPort: 8082
          name: http
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: database-credentials-secret
              key: hostname
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: database-credentials-secret
              key: port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: database-credentials-secret
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-credentials-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials-secret
              key: password
        - name: REDIS_HOST
          value: "redis.grill-stats.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secrets-secret
              key: app_secret_key
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secrets-secret
              key: jwt_secret
        - name: THERMOWORKS_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: thermoworks-api-secret
              key: client_id
        - name: THERMOWORKS_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: thermoworks-api-secret
              key: client_secret
        - name: THERMOWORKS_BASE_URL
          valueFrom:
            secretKeyRef:
              name: thermoworks-api-secret
              key: base_url
        - name: THERMOWORKS_AUTH_URL
          valueFrom:
            secretKeyRef:
              name: thermoworks-api-secret
              key: auth_url
        - name: ENCRYPTION_SERVICE_URL
          value: "http://encryption-service.grill-stats.svc.cluster.local:8082"
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: app-tmp
          mountPath: /app/tmp
      volumes:
      - name: tmp
        emptyDir: {}
      - name: app-tmp
        emptyDir: {}
      securityContext:
        fsGroup: 1000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
    component: backend
    tier: auth
spec:
  selector:
    app: auth-service
  ports:
  - port: 8082
    targetPort: 8082
    name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: auth-service-network-policy
  labels:
    app: auth-service
spec:
  podSelector:
    matchLabels:
      app: auth-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: web-ui
    - podSelector:
        matchLabels:
          app: grill-stats
    ports:
    - protocol: TCP
      port: 8082
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: postgresql
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  - to:
    - podSelector:
        matchLabels:
          app: encryption-service
    ports:
    - protocol: TCP
      port: 8082
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  labels:
    app: auth-service
data:
  LOG_LEVEL: "INFO"
  RATE_LIMIT_ATTEMPTS: "5"
  RATE_LIMIT_WINDOW: "900"
  RATE_LIMIT_LOCKOUT: "3600"
  SESSION_TIMEOUT: "86400"