apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-service
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: device-service
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: device-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: device-service
        app.kubernetes.io/part-of: grill-stats
        app.kubernetes.io/component: microservice
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: device-service
        image: lordmuffin/grill-stats-device-service:latest
        imagePullPolicy: Always
        command: ["python", "main.py"]
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: THERMOWORKS_API_KEY
          valueFrom:
            secretKeyRef:
              name: grill-stats-secrets
              key: THERMOWORKS_API_KEY
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: grill-stats-config
              key: DB_HOST
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: grill-stats-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grill-stats-secrets
              key: DB_PASSWORD
        - name: HOMEASSISTANT_URL
          valueFrom:
            secretKeyRef:
              name: grill-stats-secrets
              key: HOMEASSISTANT_URL
        - name: HOMEASSISTANT_TOKEN
          valueFrom:
            secretKeyRef:
              name: grill-stats-secrets
              key: HOMEASSISTANT_TOKEN
        - name: OTEL_SERVICE_NAME
          value: device-service
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4317"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: device-service
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: device-service
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: microservice
spec:
  selector:
    app.kubernetes.io/name: device-service
  ports:
  - port: 8080
    targetPort: http
    name: http
  type: ClusterIP
