---
apiVersion: v1
kind: Service
metadata:
  name: encryption-service
  labels:
    app: encryption-service
    component: security
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: encryption-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: encryption-service
  labels:
    app: encryption-service
    component: security
spec:
  replicas: 2
  selector:
    matchLabels:
      app: encryption-service
  template:
    metadata:
      labels:
        app: encryption-service
        component: security
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "grill-stats-encryption"
        vault.hashicorp.com/agent-inject-token: "true"
    spec:
      serviceAccountName: grill-stats-encryption
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: encryption-service
          image: grill-stats/encryption-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          env:
            - name: VAULT_URL
              value: "https://vault.vault.svc.cluster.local:8200"
            - name: VAULT_TOKEN_PATH
              value: "/vault/secrets/token"
            - name: VAULT_TRANSIT_PATH
              value: "transit"
            - name: VAULT_SKIP_VERIFY
              value: "true"
            - name: ENVIRONMENT
              value: "prod"
            - name: LOG_LEVEL
              value: "INFO"
            - name: PORT
              value: "8082"
            - name: HOST
              value: "0.0.0.0"
            - name: ENCRYPTION_RATE_LIMIT
              value: "100"
            - name: ENCRYPTION_RATE_WINDOW
              value: "60"
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: vault-secrets
              mountPath: /vault/secrets
              readOnly: true
            - name: vault-config
              mountPath: /vault/config
              readOnly: true
      volumes:
        - name: tmp
          emptyDir: {}
        - name: vault-secrets
          emptyDir:
            medium: Memory
        - name: vault-config
          configMap:
            name: vault-agent-config
# Service account moved to vault-service-accounts.yaml
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: encryption-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: encryption-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: encryption-service-config
  labels:
    app: encryption-service
data:
  transit_path: "transit"
  transit_key_name: "thermoworks-user-credentials"
  audit_log_enabled: "true"
  key_rotation_interval: "720h"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: encryption-service-network-policy
spec:
  podSelector:
    matchLabels:
      app: encryption-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: auth-service
        - podSelector:
            matchLabels:
              app: device-service
        - podSelector:
            matchLabels:
              app: temperature-service
        - podSelector:
            matchLabels:
              app: grill-stats
      ports:
        - protocol: TCP
          port: 8082
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: vault
      ports:
        - protocol: TCP
          port: 8200
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53