apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-service
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: temperature-service
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: temperature-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: temperature-service
        app.kubernetes.io/part-of: grill-stats
        app.kubernetes.io/component: microservice
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: temperature-service
        image: lordmuffin/grill-stats-temperature-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: THERMOWORKS_API_KEY
          valueFrom:
            secretKeyRef:
              name: grill-stats-secrets
              key: THERMOWORKS_API_KEY
        - name: INFLUXDB_HOST
          valueFrom:
            configMapKeyRef:
              name: grill-stats-config
              key: INFLUXDB_HOST
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: grill-stats-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grill-stats-secrets
              key: DB_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: grill-stats-config
              key: REDIS_HOST
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grill-stats-secrets
              key: REDIS_PASSWORD
        - name: SYNC_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: grill-stats-config
              key: SYNC_INTERVAL
        - name: TEMPERATURE_THRESHOLD_HIGH
          valueFrom:
            configMapKeyRef:
              name: grill-stats-config
              key: TEMPERATURE_THRESHOLD_HIGH
        - name: TEMPERATURE_THRESHOLD_LOW
          valueFrom:
            configMapKeyRef:
              name: grill-stats-config
              key: TEMPERATURE_THRESHOLD_LOW
        - name: OTEL_SERVICE_NAME
          value: temperature-service
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4317"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: temperature-service
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: temperature-service
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: microservice
spec:
  selector:
    app.kubernetes.io/name: temperature-service
  ports:
  - port: 8080
    targetPort: http
    name: http
  type: ClusterIP
