apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grill-stats-backup
  namespace: argocd
  labels:
    app.kubernetes.io/name: grill-stats-backup
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: backup
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: grill-stats
  source:
    repoURL: https://github.com/lordmuffin/grill-stats.git
    targetRevision: HEAD
    path: apps/grill-monitoring/backup/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: grill-stats
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: restricted
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/warn: restricted
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  info:
    - name: Description
      value: Backup system for Grill Stats databases and persistent data
    - name: Repository
      value: https://github.com/lordmuffin/grill-stats
    - name: Documentation
      value: https://github.com/lordmuffin/grill-stats/blob/main/apps/grill-stats/backup/README.md
  ignoreDifferences:
    - group: batch
      kind: Job
      jsonPointers:
        - /spec/template/spec/containers/0/resources
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /spec/resources/requests/storage
