apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/namespace/configmaps

patches:
  - path: patches/common-config.yaml
  - path: patches/device-service-config.yaml
  - path: patches/temperature-service-config.yaml

namespace: grill-stats-dev