apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- network-policies.yaml

commonLabels:
  app.kubernetes.io/part-of: grill-stats
  app.kubernetes.io/component: external-services
  app.kubernetes.io/managed-by: kustomize
