---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-environment-config
  namespace: grill-stats
data:
  ENVIRONMENT: "prod"
  VAULT_ADDR: "https://vault.vault.svc.cluster.local:8200"
  VAULT_SKIP_VERIFY: "false"  # Use proper TLS verification in prod
  VAULT_TRANSIT_PATH: "transit"
  VAULT_AUTH_PATH: "auth/kubernetes"
  VAULT_ROLE_PREFIX: "grill-stats"
  AUTO_ROTATE_ENABLED: "true"
  AUDIT_LOGGING_ENABLED: "true"
  MONITORING_ENABLED: "true"
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS_PER_SECOND: "200"  # Higher limit for prod
  RATE_LIMIT_BURST: "400"
  TOKEN_RENEWAL_THRESHOLD: "3600"
  TOKEN_MAX_TTL: "86400"
  ENCRYPTION_BATCH_SIZE: "200"  # Larger batch size for prod
  ENCRYPTION_TIMEOUT: "30s"
  KEY_ROTATION_NOTIFICATION_ENABLED: "true"
  BACKUP_ENABLED: "true"
  BACKUP_RETENTION_DAYS: "90"
  KEY_ROTATION_INTERVAL: "2160h"  # 90 days for prod
  MAX_KEY_AGE_DAYS: "90"
  DRY_RUN: "false"
  LOG_LEVEL: "INFO"
  SECURITY_HARDENING_ENABLED: "true"
  NETWORK_POLICY_ENABLED: "true"
  POD_SECURITY_POLICY_ENABLED: "true"
  RESOURCE_QUOTAS_ENABLED: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent
  namespace: grill-stats
spec:
  replicas: 2  # High availability for prod
  template:
    spec:
      containers:
      - name: vault-agent
        env:
        - name: ENVIRONMENT
          value: "prod"
        - name: VAULT_ADDR
          value: "https://vault.vault.svc.cluster.local:8200"
        - name: VAULT_SKIP_VERIFY
          value: "false"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: vault-tls-cert
          mountPath: /vault/tls
          readOnly: true
      volumes:
      - name: vault-tls-cert
        secret:
          secretName: vault-tls-cert
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: key-rotation-cronjob
  namespace: grill-stats
spec:
  schedule: "0 2 * * 0"  # Weekly on Sunday at 2 AM for prod
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: key-rotation
            env:
            - name: ENVIRONMENT
              value: "prod"
            - name: VAULT_ADDR
              value: "https://vault.vault.svc.cluster.local:8200"
            - name: ROTATION_INTERVAL_HOURS
              value: "2160"  # 90 days
            - name: MAX_KEY_AGE_DAYS
              value: "90"
            - name: DRY_RUN
              value: "false"
            - name: LOG_LEVEL
              value: "INFO"
            - name: BACKUP_ENABLED
              value: "true"
            - name: NOTIFICATION_ENABLED
              value: "true"
            resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "512Mi"
                cpu: "500m"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vault-agent-pdb
  namespace: grill-stats
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: vault-agent
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vault-agent-hpa
  namespace: grill-stats
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vault-agent
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 180
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
