---
# PostgreSQL Production Environment Patches
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: grill-stats
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: postgresql
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 2Gi
        env:
        - name: POSTGRES_INITDB_ARGS
          value: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      - name: postgres-exporter
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
  volumeClaimTemplates:
  - metadata:
      name: postgresql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Gi
---
# PostgreSQL Production Configuration Override
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: grill-stats
data:
  postgresql.conf: |
    # PostgreSQL Production Configuration
    # Connection Settings
    listen_addresses = '*'
    port = 5432
    max_connections = 200
    superuser_reserved_connections = 5
    
    # Memory Settings - Optimized for production
    shared_buffers = 512MB
    effective_cache_size = 1GB
    maintenance_work_mem = 128MB
    work_mem = 8MB
    
    # Checkpoint Settings
    checkpoint_completion_target = 0.9
    wal_buffers = 32MB
    
    # Query Planner Settings
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    
    # Write Ahead Log Settings - Production with replication
    wal_level = replica
    max_wal_senders = 5
    max_replication_slots = 5
    wal_keep_segments = 64
    archive_mode = on
    archive_command = 'test ! -f /var/lib/postgresql/archive/%f && cp %p /var/lib/postgresql/archive/%f'
    
    # Logging Settings - Production appropriate
    logging_collector = on
    log_destination = 'stderr'
    log_directory = '/var/lib/postgresql/data/pg_log'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_truncate_on_rotation = on
    log_rotation_age = 1d
    log_rotation_size = 100MB
    log_min_duration_statement = 5000
    log_checkpoints = on
    log_connections = off
    log_disconnections = off
    log_lock_waits = on
    log_statement = 'ddl'
    log_temp_files = 0
    log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
    
    # Security Settings - Production hardened
    ssl = on
    ssl_ciphers = 'HIGH:MEDIUM:+3DES:!aNULL'
    ssl_prefer_server_ciphers = on
    password_encryption = scram-sha-256
    
    # Performance Settings
    shared_preload_libraries = 'pg_stat_statements'
    track_activity_query_size = 2048
    pg_stat_statements.max = 10000
    pg_stat_statements.track = all
    
    # Autovacuum Settings - Production optimized
    autovacuum = on
    autovacuum_max_workers = 4
    autovacuum_naptime = 1min
    autovacuum_vacuum_threshold = 50
    autovacuum_analyze_threshold = 50
    autovacuum_vacuum_scale_factor = 0.2
    autovacuum_analyze_scale_factor = 0.1
    autovacuum_freeze_max_age = 200000000
    autovacuum_multixact_freeze_max_age = 400000000
    autovacuum_vacuum_cost_delay = 10ms
    autovacuum_vacuum_cost_limit = 500
    
    # Lock Settings
    deadlock_timeout = 1s
    max_locks_per_transaction = 64
    
    # Background Writer Settings
    bgwriter_delay = 200ms
    bgwriter_lru_maxpages = 100
    bgwriter_lru_multiplier = 2.0
    bgwriter_flush_after = 512kB
    
    # Write Ahead Log Settings
    wal_compression = on
    wal_log_hints = on
    checkpoint_timeout = 5min
    max_wal_size = 2GB
    min_wal_size = 160MB
    checkpoint_flush_after = 256kB
    
    # Parallel Query Settings
    max_parallel_workers_per_gather = 4
    max_parallel_workers = 8
    max_parallel_maintenance_workers = 4
    
    # Time Zone
    timezone = 'UTC'
    
    # JIT Settings - Enabled for production
    jit = on
    jit_above_cost = 100000
    jit_inline_above_cost = 500000
    jit_optimize_above_cost = 500000
---
# PostgreSQL Host-Based Authentication for Production
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-hba-config
  namespace: grill-stats
data:
  pg_hba.conf: |
    # PostgreSQL Client Authentication Configuration File - Production
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    
    # "local" is for Unix domain socket connections only
    local   all             postgres                                peer
    
    # IPv4 local connections:
    host    all             postgres        127.0.0.1/32            scram-sha-256
    host    all             postgres        ::1/128                 scram-sha-256
    
    # Allow replication connections from localhost, by a user with the
    # replication privilege.
    local   replication     postgres                                peer
    host    replication     postgres        127.0.0.1/32            scram-sha-256
    host    replication     postgres        ::1/128                 scram-sha-256
    
    # Application connections - restricted to internal networks
    host    grill_stats     grill_stats_user    10.0.0.0/8          scram-sha-256
    host    grill_stats     grill_stats_user    172.16.0.0/12       scram-sha-256
    host    grill_stats     grill_stats_user    192.168.0.0/16      scram-sha-256
    
    # Service-specific connections
    host    grill_stats     auth_service        10.0.0.0/8          scram-sha-256
    host    grill_stats     device_service      10.0.0.0/8          scram-sha-256
    host    grill_stats     encryption_service  10.0.0.0/8          scram-sha-256
    host    grill_stats     temperature_service 10.0.0.0/8          scram-sha-256
    host    grill_stats     historical_service  10.0.0.0/8          scram-sha-256
    
    # Read-only connections
    host    grill_stats     readonly_user       10.0.0.0/8          scram-sha-256
    host    grill_stats     readonly_user       172.16.0.0/12       scram-sha-256
    host    grill_stats     readonly_user       192.168.0.0/16      scram-sha-256
    
    # Backup connections
    host    grill_stats     backup_user         10.0.0.0/8          scram-sha-256
    
    # Monitoring connections
    host    grill_stats     monitoring_user     10.0.0.0/8          scram-sha-256
    
    # Replication connections for HA
    host    replication     replication_user    10.0.0.0/8          scram-sha-256
    host    replication     replication_user    172.16.0.0/12       scram-sha-256
    host    replication     replication_user    192.168.0.0/16      scram-sha-256
    
    # Deny all other connections
    host    all             all                 0.0.0.0/0           reject
    host    all             all                 ::/0                reject