apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: temperature-data
  namespace: grill-monitoring
  labels:
    strimzi.io/cluster: grill-stats-kafka
spec:
  partitions: 6
  replicas: 3
  config:
    retention.ms: 604800000  # 7 days
    segment.bytes: 1073741824  # 1 GB
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: device-events
  namespace: grill-monitoring
  labels:
    strimzi.io/cluster: grill-stats-kafka
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 259200000  # 3 days
    segment.bytes: 1073741824  # 1 GB
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: temperature-alerts
  namespace: grill-monitoring
  labels:
    strimzi.io/cluster: grill-stats-kafka
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 604800000  # 7 days
    segment.bytes: 1073741824  # 1 GB