---
# Authentication Service 1Password Connect Configuration
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: auth-service-secrets-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: auth-service
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/grill-stats/items/auth-service-secrets"
---
# Authentication Service Secrets
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: auth-service
    managed-by: onepassword-connect
  annotations:
    onepassword.com/item-path: "vaults/grill-stats/items/auth-service-secrets"
type: Opaque
stringData:
  # JWT Configuration
  jwt-secret: ""
  jwt-algorithm: "HS256"

  # Session Configuration
  session-secret: ""
  session-lifetime: "86400"

  # Database Configuration
  database-url: ""
  database-host: ""
  database-port: "5432"
  database-name: "grill_stats"
  database-user: ""
  database-password: ""

  # Redis Configuration
  redis-host: ""
  redis-port: "6379"
  redis-password: ""
  redis-url: ""

  # ThermoWorks API Configuration
  thermoworks-client-id: ""
  thermoworks-client-secret: ""
  thermoworks-base-url: "https://api.thermoworks.com"
  thermoworks-auth-url: "https://auth.thermoworks.com"

  # Rate Limiting Configuration
  rate-limit-attempts: "5"
  rate-limit-window: "900"
  rate-limit-lockout: "3600"

  # Security Configuration
  bcrypt-rounds: "12"
  password-min-length: "8"
---
# Authentication Service Database User Secret
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: auth-service-db-user-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: auth-service
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/grill-stats/items/auth-service-db-user"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-db-user
  namespace: grill-stats
  labels:
    app: grill-stats
    component: auth-service
    managed-by: onepassword-connect
  annotations:
    onepassword.com/item-path: "vaults/grill-stats/items/auth-service-db-user"
type: Opaque
stringData:
  username: ""
  password: ""
  readonly-username: ""
  readonly-password: ""
