---
# PostgreSQL Database 1Password Connect Configuration
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgresql-secrets-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: database
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/grill-stats/items/postgresql-secrets"
---
# PostgreSQL Database Secrets
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: database
    managed-by: onepassword-connect
  annotations:
    onepassword.com/item-path: "vaults/grill-stats/items/postgresql-secrets"
type: Opaque
stringData:
  # PostgreSQL Admin Configuration
  postgres-password: ""
  postgres-user: "postgres"
  postgres-database: "postgres"
  
  # Application Database Configuration
  database-name: "grill_stats"
  database-user: ""
  database-password: ""
  database-url: ""
  
  # Service-Specific Users
  auth-service-user: ""
  auth-service-password: ""
  device-service-user: ""
  device-service-password: ""
  encryption-service-user: ""
  encryption-service-password: ""
  
  # Read-Only Users
  readonly-user: ""
  readonly-password: ""
  backup-user: ""
  backup-password: ""
  
  # Connection Configuration
  max-connections: "100"
  shared-buffers: "128MB"
  effective-cache-size: "1GB"
  maintenance-work-mem: "64MB"
  
  # SSL Configuration
  ssl-mode: "require"
  ssl-cert: ""
  ssl-key: ""
  ssl-ca: ""
  
  # Monitoring and Backup Configuration
  monitoring-user: ""
  monitoring-password: ""
  backup-webhook-url: ""
  
  # High Availability Configuration
  replication-user: ""
  replication-password: ""
  
  # Database Connection URLs
  database-url: ""
  readonly-database-url: ""
  backup-database-url: ""
  
  # Service Connection Strings
  auth-service-url: ""
  device-service-url: ""
  encryption-service-url: ""
  temperature-service-url: ""
  historical-service-url: ""
---
# InfluxDB 1Password Connect Configuration
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: influxdb-secrets-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: database
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/grill-stats/items/influxdb-secrets"
---
# InfluxDB Secrets
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: database
    managed-by: onepassword-connect
  annotations:
    onepassword.com/item-path: "vaults/grill-stats/items/influxdb-secrets"
type: Opaque
stringData:
  # InfluxDB Admin Configuration
  influxdb-admin-user: ""
  influxdb-admin-password: ""
  influxdb-admin-token: ""
  
  # InfluxDB Organization & Bucket
  influxdb-org: "grill-stats"
  influxdb-bucket: "temperature-data"
  influxdb-retention: "720h"
  
  # Application User Configuration
  influxdb-user: ""
  influxdb-password: ""
  influxdb-token: ""
  influxdb-url: ""
  
  # Read-Only User Configuration
  influxdb-readonly-user: ""
  influxdb-readonly-password: ""
  influxdb-readonly-token: ""
  
  # Service-Specific Tokens
  temperature-service-token: ""
  historical-service-token: ""
  web-ui-token: ""
  
  # Configuration
  influxdb-precision: "s"
  influxdb-timeout: "30s"
  influxdb-max-retries: "3"
---
# Redis 1Password Connect Configuration
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: redis-secrets-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: database
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/grill-stats/items/redis-secrets"
---
# Redis Secrets
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: database
    managed-by: onepassword-connect
  annotations:
    onepassword.com/item-path: "vaults/grill-stats/items/redis-secrets"
type: Opaque
stringData:
  # Redis Configuration
  redis-password: ""
  redis-url: ""
  redis-host: ""
  redis-port: "6379"
  
  # Redis Sentinel Configuration
  redis-sentinel-password: ""
  redis-sentinel-service-name: "grill-stats-redis"
  
  # Redis Cluster Configuration
  redis-cluster-enabled: "false"
  redis-cluster-nodes: ""
  
  # Performance Configuration
  redis-max-memory: "1gb"
  redis-max-memory-policy: "allkeys-lru"
  redis-timeout: "5s"
  redis-pool-size: "10"
  
  # Security Configuration
  redis-ssl-enabled: "false"
  redis-ssl-cert: ""
  redis-ssl-key: ""
  redis-ssl-ca: ""
---
# TimescaleDB 1Password Connect Configuration
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: timescaledb-secrets-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: database
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/grill-stats/items/timescaledb-secrets"
---
# TimescaleDB Secrets
apiVersion: v1
kind: Secret
metadata:
  name: timescaledb-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: database
    managed-by: onepassword-connect
  annotations:
    onepassword.com/item-path: "vaults/grill-stats/items/timescaledb-secrets"
type: Opaque
stringData:
  # TimescaleDB Admin Configuration
  timescale-admin-user: ""
  timescale-admin-password: ""
  timescale-database: "grill_stats_historical"
  
  # Application User Configuration
  timescale-user: ""
  timescale-password: ""
  timescale-url: ""
  
  # Read-Only User Configuration
  timescale-readonly-user: ""
  timescale-readonly-password: ""
  
  # Backup User Configuration
  timescale-backup-user: ""
  timescale-backup-password: ""
  
  # Connection Configuration
  timescale-host: ""
  timescale-port: "5432"
  timescale-ssl-mode: "require"
  timescale-connect-timeout: "30"
  timescale-max-connections: "20"
  
  # Performance Configuration
  timescale-chunk-time-interval: "1 day"
  timescale-compression-policy: "7 days"
  timescale-retention-policy: "365 days"