---
# Device Service 1Password Connect Configuration
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: device-service-secrets-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: device-service
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/grill-stats/items/device-service-secrets"
---
# Device Service Secrets
apiVersion: v1
kind: Secret
metadata:
  name: device-service-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: device-service
    managed-by: onepassword-connect
  annotations:
    onepassword.com/item-path: "vaults/grill-stats/items/device-service-secrets"
type: Opaque
stringData:
  # JWT Configuration
  jwt-secret: ""
  jwt-algorithm: "HS256"

  # Database Configuration
  database-url: ""
  database-host: ""
  database-port: "5432"
  database-name: "grill_stats"
  database-user: ""
  database-password: ""

  # Redis Configuration
  redis-host: ""
  redis-port: "6379"
  redis-password: ""
  redis-url: ""

  # ThermoWorks API Configuration
  thermoworks-client-id: ""
  thermoworks-client-secret: ""
  thermoworks-base-url: "https://api.thermoworks.com"
  thermoworks-auth-url: "https://auth.thermoworks.com"
  thermoworks-api-key: ""
  thermoworks-api-secret: ""

  # Device Management Configuration
  device-discovery-interval: "60"
  device-sync-interval: "300"
  device-timeout: "30"
  device-retry-attempts: "3"

  # OAuth2 Configuration
  oauth2-client-id: ""
  oauth2-client-secret: ""
  oauth2-redirect-uri: ""
  oauth2-scope: "devices:read temperature:read"

  # RFX Gateway Configuration
  rfx-gateway-url: ""
  rfx-gateway-api-key: ""
  rfx-gateway-timeout: "30"

  # Home Assistant Configuration
  homeassistant-url: ""
  homeassistant-token: ""
  homeassistant-ssl-verify: "true"
---
# Device Service Database User Secret
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: device-service-db-user-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: device-service
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/grill-stats/items/device-service-db-user"
---
apiVersion: v1
kind: Secret
metadata:
  name: device-service-db-user
  namespace: grill-stats
  labels:
    app: grill-stats
    component: device-service
    managed-by: onepassword-connect
  annotations:
    onepassword.com/item-path: "vaults/grill-stats/items/device-service-db-user"
type: Opaque
stringData:
  username: ""
  password: ""
  readonly-username: ""
  readonly-password: ""
