---
# Encryption Service 1Password Connect Configuration
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: encryption-service-secrets-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: encryption-service
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/grill-stats/items/encryption-service-secrets"
---
# Encryption Service Secrets
apiVersion: v1
kind: Secret
metadata:
  name: encryption-service-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: encryption-service
    managed-by: onepassword-connect
  annotations:
    onepassword.com/item-path: "vaults/grill-stats/items/encryption-service-secrets"
type: Opaque
stringData:
  # JWT Configuration
  jwt-secret: ""
  jwt-algorithm: "HS256"
  
  # HashiCorp Vault Configuration
  vault-url: ""
  vault-token: ""
  vault-role-id: ""
  vault-secret-id: ""
  vault-namespace: ""
  vault-mount-path: "transit"
  vault-key-name: "grill-stats-encryption-key"
  vault-ca-cert: ""
  vault-client-cert: ""
  vault-client-key: ""
  
  # Encryption Configuration
  encryption-algorithm: "AES256-GCM"
  encryption-key-version: "1"
  encryption-key-rotation-days: "90"
  encryption-context: "grill-stats-credentials"
  
  # Rate Limiting Configuration
  rate-limit-requests: "100"
  rate-limit-window: "3600"
  rate-limit-burst: "20"
  
  # Audit Configuration
  audit-enabled: "true"
  audit-log-level: "INFO"
  audit-retention-days: "180"
  audit-encryption-key: ""
  
  # Database Configuration (for audit logs)
  database-url: ""
  database-host: ""
  database-port: "5432"
  database-name: "grill_stats_audit"
  database-user: ""
  database-password: ""
  
  # Redis Configuration (for rate limiting)
  redis-host: ""
  redis-port: "6379"
  redis-password: ""
  redis-url: ""
  redis-cache-ttl: "300"
  
  # Health Check Configuration
  health-check-interval: "30"
  health-check-timeout: "10"
  health-check-retries: "3"
  
  # Performance Configuration
  concurrent-requests: "10"
  request-timeout: "30"
  connection-pool-size: "5"
---
# Encryption Service Vault Token Secret
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: encryption-service-vault-token-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: encryption-service
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/grill-stats/items/encryption-service-vault-token"
---
apiVersion: v1
kind: Secret
metadata:
  name: encryption-service-vault-token
  namespace: grill-stats
  labels:
    app: grill-stats
    component: encryption-service
    managed-by: onepassword-connect
  annotations:
    onepassword.com/item-path: "vaults/grill-stats/items/encryption-service-vault-token"
type: Opaque
stringData:
  root-token: ""
  service-token: ""
  admin-token: ""
  readonly-token: ""
  rotation-token: ""