---
# Historical Data Service 1Password Connect Configuration
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: historical-data-service-secrets-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: historical-data-service
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/grill-stats/items/historical-data-service-secrets"
---
# Historical Data Service Secrets
apiVersion: v1
kind: Secret
metadata:
  name: historical-data-service-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: historical-data-service
    managed-by: onepassword-connect
  annotations:
    onepassword.com/item-path: "vaults/grill-stats/items/historical-data-service-secrets"
type: Opaque
stringData:
  # JWT Configuration
  jwt-secret: ""
  jwt-algorithm: "HS256"
  
  # TimescaleDB Configuration
  timescale-url: ""
  timescale-host: ""
  timescale-port: "5432"
  timescale-database: "grill_stats_historical"
  timescale-username: ""
  timescale-password: ""
  timescale-ssl-mode: "require"
  
  # InfluxDB Configuration (for data migration)
  influxdb-url: ""
  influxdb-token: ""
  influxdb-org: ""
  influxdb-bucket: ""
  influxdb-username: ""
  influxdb-password: ""
  
  # Redis Configuration
  redis-host: ""
  redis-port: "6379"
  redis-password: ""
  redis-url: ""
  redis-cache-ttl: "3600"
  
  # Data Retention Configuration
  data-retention-days: "365"
  data-compression-days: "30"
  data-archive-days: "90"
  data-backup-interval: "24"
  
  # Query Configuration
  query-timeout: "300"
  query-max-rows: "100000"
  query-batch-size: "1000"
  
  # API Configuration
  api-rate-limit: "1000"
  api-rate-window: "3600"
  api-max-concurrent: "10"
  
  # Analytics Configuration
  analytics-enabled: "true"
  analytics-aggregation-interval: "300"
  analytics-retention-days: "90"
---
# Historical Data Service TimescaleDB User Secret
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: historical-data-service-timescale-user-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: historical-data-service
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/grill-stats/items/historical-data-service-timescale-user"
---
apiVersion: v1
kind: Secret
metadata:
  name: historical-data-service-timescale-user
  namespace: grill-stats
  labels:
    app: grill-stats
    component: historical-data-service
    managed-by: onepassword-connect
  annotations:
    onepassword.com/item-path: "vaults/grill-stats/items/historical-data-service-timescale-user"
type: Opaque
stringData:
  username: ""
  password: ""
  readonly-username: ""
  readonly-password: ""
  backup-username: ""
  backup-password: ""