apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: grill-stats-secrets-base
  annotations:
    config.kubernetes.io/local-config: "true"

namespace: grill-stats

# Base resources for all grill-stats secrets
resources:
  # Service-specific 1Password secrets
  - auth-service-1password.yaml
  - device-service-1password.yaml
  - temperature-service-1password.yaml
  - historical-data-service-1password.yaml
  - encryption-service-1password.yaml
  - web-ui-1password.yaml

  # Shared database secrets
  - databases-1password.yaml

  # RBAC configurations
  - rbac-1password.yaml

commonLabels:
  app.kubernetes.io/name: grill-stats
  app.kubernetes.io/component: secrets
  app.kubernetes.io/part-of: grill-stats-platform
  app.kubernetes.io/managed-by: onepassword-connect
  onepassword.com/managed: "true"

commonAnnotations:
  config.kubernetes.io/local-config: "true"
  onepassword.com/vault: "grill-stats"
  onepassword.com/version: "v1.0.0"
  deployment.kubernetes.io/revision: "1"

# Configuration for secret management
configMapGenerator:
- name: grill-stats-secrets-config
  literals:
    - environment=base
    - vault-name=grill-stats
    - secret-rotation-days=90
    - backup-enabled=true
    - monitoring-enabled=true
    - audit-enabled=true

# Secret generator for common configurations
secretGenerator:
- name: grill-stats-common-config
  literals:
    - log-level=INFO
    - health-check-interval=30
    - metrics-port=9090
    - debug-enabled=false

# Patches for common configurations
patchesStrategicMerge:
- |
  apiVersion: v1
  kind: Secret
  metadata:
    name: auth-service-secrets
    namespace: grill-stats
  stringData:
    common-log-level: INFO
    common-health-check-interval: "30"
    common-metrics-enabled: "true"

# Images for secret management tools
images:
- name: onepassword/connect-api
  newTag: 1.7.2
- name: onepassword/connect-sync
  newTag: 1.7.2

# Transformers for secret management
transformers:
- |
  apiVersion: builtin
  kind: NamespaceTransformer
  metadata:
    name: namespace-transformer
  namespace: grill-stats
  setRoleBindingSubjects: namespace
  unsetOnly: false

# Replacements for dynamic values
replacements:
- source:
    kind: ConfigMap
    name: grill-stats-secrets-config
    fieldPath: data.vault-name
  targets:
  - select:
      kind: OnePasswordItem
    fieldPaths:
    - spec.itemPath
    options:
      delimiter: "/"
      index: 1

# Generators for environment-specific configurations
generators:
- |
  apiVersion: builtin
  kind: ConfigMapGenerator
  metadata:
    name: environment-config
  literals:
    - environment=base
    - cluster-name=grill-stats
    - region=homelab
    - deployment-time=$(date -u +%Y%m%d%H%M%S)

# Validation rules
validators:
- |
  apiVersion: builtin
  kind: ValidatorTransformer
  metadata:
    name: secret-validator
  rules:
  - apiVersion: v1
    kind: Secret
    jsonSchema:
      type: object
      properties:
        metadata:
          type: object
          properties:
            labels:
              type: object
              required:
              - app.kubernetes.io/name
              - app.kubernetes.io/component
              - managed-by
            annotations:
              type: object
              required:
              - onepassword.com/item-path
        type:
          enum:
          - Opaque
      required:
      - metadata
      - type
