---
# Grill Stats Secrets Management Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grill-stats-secrets-manager
  namespace: grill-stats
  labels:
    app: grill-stats
    component: secrets
    managed-by: onepassword-connect
  annotations:
    onepassword.com/service-account: "true"
---
# Grill Stats Secrets Management Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grill-stats-secrets-manager
  namespace: grill-stats
  labels:
    app: grill-stats
    component: secrets
    managed-by: onepassword-connect
rules:
# Secret management
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# OnePassword Connect resources
- apiGroups: ["onepassword.com"]
  resources: ["onepassworditems"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# ConfigMap access for configuration
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Events for auditing
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
# Grill Stats Secrets Management RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grill-stats-secrets-manager
  namespace: grill-stats
  labels:
    app: grill-stats
    component: secrets
    managed-by: onepassword-connect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grill-stats-secrets-manager
subjects:
- kind: ServiceAccount
  name: grill-stats-secrets-manager
  namespace: grill-stats
---
# Auth Service Secret Access Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: auth-service
    managed-by: onepassword-connect
---
# Auth Service Secret Access Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: auth-service-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: auth-service
    managed-by: onepassword-connect
rules:
# Auth service specific secrets
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: 
    - "auth-service-secrets"
    - "auth-service-db-user"
    - "postgresql-secrets"
    - "redis-secrets"
    - "jwt-secrets-secret"
    - "thermoworks-api-secret"
  verbs: ["get", "list", "watch"]
# OnePassword Connect resources for auth service
- apiGroups: ["onepassword.com"]
  resources: ["onepassworditems"]
  resourceNames:
    - "auth-service-secrets-1password"
    - "auth-service-db-user-1password"
  verbs: ["get", "list", "watch"]
---
# Auth Service Secret Access RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auth-service-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: auth-service
    managed-by: onepassword-connect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: auth-service-secrets
subjects:
- kind: ServiceAccount
  name: auth-service-secrets
  namespace: grill-stats
---
# Device Service Secret Access Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: device-service-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: device-service
    managed-by: onepassword-connect
---
# Device Service Secret Access Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: device-service-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: device-service
    managed-by: onepassword-connect
rules:
# Device service specific secrets
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: 
    - "device-service-secrets"
    - "device-service-db-user"
    - "postgresql-secrets"
    - "redis-secrets"
    - "thermoworks-api-secret"
  verbs: ["get", "list", "watch"]
# OnePassword Connect resources for device service
- apiGroups: ["onepassword.com"]
  resources: ["onepassworditems"]
  resourceNames:
    - "device-service-secrets-1password"
    - "device-service-db-user-1password"
  verbs: ["get", "list", "watch"]
---
# Device Service Secret Access RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: device-service-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: device-service
    managed-by: onepassword-connect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: device-service-secrets
subjects:
- kind: ServiceAccount
  name: device-service-secrets
  namespace: grill-stats
---
# Temperature Service Secret Access Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: temperature-service-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: temperature-service
    managed-by: onepassword-connect
---
# Temperature Service Secret Access Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: temperature-service-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: temperature-service
    managed-by: onepassword-connect
rules:
# Temperature service specific secrets
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: 
    - "temperature-service-secrets"
    - "temperature-service-influxdb-user"
    - "influxdb-secrets"
    - "redis-secrets"
    - "thermoworks-api-secret"
  verbs: ["get", "list", "watch"]
# OnePassword Connect resources for temperature service
- apiGroups: ["onepassword.com"]
  resources: ["onepassworditems"]
  resourceNames:
    - "temperature-service-secrets-1password"
    - "temperature-service-influxdb-user-1password"
  verbs: ["get", "list", "watch"]
---
# Temperature Service Secret Access RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: temperature-service-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: temperature-service
    managed-by: onepassword-connect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: temperature-service-secrets
subjects:
- kind: ServiceAccount
  name: temperature-service-secrets
  namespace: grill-stats
---
# Historical Data Service Secret Access Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: historical-data-service-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: historical-data-service
    managed-by: onepassword-connect
---
# Historical Data Service Secret Access Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: historical-data-service-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: historical-data-service
    managed-by: onepassword-connect
rules:
# Historical data service specific secrets
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: 
    - "historical-data-service-secrets"
    - "historical-data-service-timescale-user"
    - "timescaledb-secrets"
    - "influxdb-secrets"
    - "redis-secrets"
  verbs: ["get", "list", "watch"]
# OnePassword Connect resources for historical data service
- apiGroups: ["onepassword.com"]
  resources: ["onepassworditems"]
  resourceNames:
    - "historical-data-service-secrets-1password"
    - "historical-data-service-timescale-user-1password"
  verbs: ["get", "list", "watch"]
---
# Historical Data Service Secret Access RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: historical-data-service-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: historical-data-service
    managed-by: onepassword-connect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: historical-data-service-secrets
subjects:
- kind: ServiceAccount
  name: historical-data-service-secrets
  namespace: grill-stats
---
# Encryption Service Secret Access Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: encryption-service-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: encryption-service
    managed-by: onepassword-connect
---
# Encryption Service Secret Access Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: encryption-service-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: encryption-service
    managed-by: onepassword-connect
rules:
# Encryption service specific secrets
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: 
    - "encryption-service-secrets"
    - "encryption-service-vault-token"
    - "vault-token-secret"
    - "vault-admin-token-secret"
    - "postgresql-secrets"
    - "redis-secrets"
  verbs: ["get", "list", "watch"]
# OnePassword Connect resources for encryption service
- apiGroups: ["onepassword.com"]
  resources: ["onepassworditems"]
  resourceNames:
    - "encryption-service-secrets-1password"
    - "encryption-service-vault-token-1password"
  verbs: ["get", "list", "watch"]
---
# Encryption Service Secret Access RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: encryption-service-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: encryption-service
    managed-by: onepassword-connect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: encryption-service-secrets
subjects:
- kind: ServiceAccount
  name: encryption-service-secrets
  namespace: grill-stats
---
# Web UI Service Secret Access Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-ui-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: web-ui
    managed-by: onepassword-connect
---
# Web UI Service Secret Access Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: web-ui-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: web-ui
    managed-by: onepassword-connect
rules:
# Web UI service specific secrets
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: 
    - "web-ui-secrets"
    - "web-ui-api-keys"
  verbs: ["get", "list", "watch"]
# OnePassword Connect resources for web UI service
- apiGroups: ["onepassword.com"]
  resources: ["onepassworditems"]
  resourceNames:
    - "web-ui-secrets-1password"
    - "web-ui-api-keys-1password"
  verbs: ["get", "list", "watch"]
---
# Web UI Service Secret Access RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-ui-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: web-ui
    managed-by: onepassword-connect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-ui-secrets
subjects:
- kind: ServiceAccount
  name: web-ui-secrets
  namespace: grill-stats