---
# Temperature Service 1Password Connect Configuration
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: temperature-service-secrets-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: temperature-service
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/grill-stats/items/temperature-service-secrets"
---
# Temperature Service Secrets
apiVersion: v1
kind: Secret
metadata:
  name: temperature-service-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: temperature-service
    managed-by: onepassword-connect
  annotations:
    onepassword.com/item-path: "vaults/grill-stats/items/temperature-service-secrets"
type: Opaque
stringData:
  # JWT Configuration
  jwt-secret: ""
  jwt-algorithm: "HS256"

  # InfluxDB Configuration
  influxdb-url: ""
  influxdb-token: ""
  influxdb-org: ""
  influxdb-bucket: ""
  influxdb-username: ""
  influxdb-password: ""
  influxdb-database: "grill_stats"

  # Redis Configuration
  redis-host: ""
  redis-port: "6379"
  redis-password: ""
  redis-url: ""
  redis-cache-ttl: "300"

  # ThermoWorks API Configuration
  thermoworks-client-id: ""
  thermoworks-client-secret: ""
  thermoworks-base-url: "https://api.thermoworks.com"
  thermoworks-auth-url: "https://auth.thermoworks.com"
  thermoworks-api-key: ""
  thermoworks-api-secret: ""

  # Temperature Data Configuration
  temperature-retention-days: "30"
  temperature-sampling-interval: "5"
  temperature-batch-size: "100"
  temperature-alert-threshold: "200"

  # Health Check Configuration
  health-check-interval: "30"
  health-check-timeout: "10"
  health-check-retries: "3"

  # Streaming Configuration
  streaming-enabled: "true"
  streaming-port: "8084"
  streaming-buffer-size: "1000"
---
# Temperature Service InfluxDB User Secret
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: temperature-service-influxdb-user-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: temperature-service
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/grill-stats/items/temperature-service-influxdb-user"
---
apiVersion: v1
kind: Secret
metadata:
  name: temperature-service-influxdb-user
  namespace: grill-stats
  labels:
    app: grill-stats
    component: temperature-service
    managed-by: onepassword-connect
  annotations:
    onepassword.com/item-path: "vaults/grill-stats/items/temperature-service-influxdb-user"
type: Opaque
stringData:
  username: ""
  password: ""
  token: ""
  readonly-username: ""
  readonly-password: ""
  readonly-token: ""
