---
# Web UI Service 1Password Connect Configuration
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: web-ui-secrets-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: web-ui
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/grill-stats/items/web-ui-secrets"
---
# Web UI Service Secrets
apiVersion: v1
kind: Secret
metadata:
  name: web-ui-secrets
  namespace: grill-stats
  labels:
    app: grill-stats
    component: web-ui
    managed-by: onepassword-connect
  annotations:
    onepassword.com/item-path: "vaults/grill-stats/items/web-ui-secrets"
type: Opaque
stringData:
  # API Configuration
  api-base-url: ""
  api-timeout: "30000"
  api-retry-attempts: "3"
  api-retry-delay: "1000"

  # Authentication Configuration
  auth-service-url: ""
  jwt-secret: ""
  session-timeout: "86400"
  auto-refresh-token: "true"

  # Device Service Configuration
  device-service-url: ""
  device-polling-interval: "5000"
  device-connection-timeout: "10000"

  # Temperature Service Configuration
  temperature-service-url: ""
  temperature-streaming-url: ""
  temperature-update-interval: "1000"
  temperature-chart-points: "100"

  # Historical Data Service Configuration
  historical-service-url: ""
  historical-data-limit: "1000"
  historical-chart-resolution: "minute"

  # WebSocket Configuration
  websocket-url: ""
  websocket-reconnect: "true"
  websocket-reconnect-interval: "5000"
  websocket-max-reconnect: "10"

  # Feature Flags
  feature-real-time-charts: "true"
  feature-historical-charts: "true"
  feature-device-management: "true"
  feature-alerts: "true"
  feature-export: "true"

  # Performance Configuration
  cache-enabled: "true"
  cache-ttl: "300"
  compression-enabled: "true"
  lazy-loading: "true"

  # Security Configuration
  csp-enabled: "true"
  cors-origins: ""
  security-headers: "true"

  # Analytics Configuration
  analytics-enabled: "false"
  analytics-tracking-id: ""
  error-reporting-enabled: "true"
  error-reporting-dsn: ""

  # Development Configuration
  dev-mode: "false"
  debug-enabled: "false"
  hot-reload: "false"
---
# Web UI Service API Keys Secret
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: web-ui-api-keys-1password
  namespace: grill-stats
  labels:
    app: grill-stats
    component: web-ui
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/grill-stats/items/web-ui-api-keys"
---
apiVersion: v1
kind: Secret
metadata:
  name: web-ui-api-keys
  namespace: grill-stats
  labels:
    app: grill-stats
    component: web-ui
    managed-by: onepassword-connect
  annotations:
    onepassword.com/item-path: "vaults/grill-stats/items/web-ui-api-keys"
type: Opaque
stringData:
  auth-api-key: ""
  device-api-key: ""
  temperature-api-key: ""
  historical-api-key: ""
  encryption-api-key: ""
  internal-api-key: ""
