global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - rules/database-alerts.yaml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: postgres-exporter
    static_configs:
      - targets:
          - postgres-exporter:9187
    metrics_path: /metrics

  - job_name: influxdb
    static_configs:
      - targets:
          - influxdb:8086
    metrics_path: /metrics

  - job_name: redis-exporter
    static_configs:
      - targets:
          - redis-exporter:9121
    metrics_path: /metrics

  - job_name: grill-stats
    static_configs:
      - targets:
          - grill-stats:5000
    metrics_path: /metrics
