apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grill-stats
  namespace: argocd
spec:
  project: default  # Use your ArgoCD project name
  source:
    repoURL: https://gitea.lab.apj.dev/lordmuffin/homelab.git  # Update with your actual repository URL
    targetRevision: HEAD
    path: apps/services/grill-stats  # Path in your homelab repository
  destination:
    server: https://kubernetes.default.svc
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true