apiVersion: v1
kind: ConfigMap
metadata:
  name: grill-monitoring-config
  namespace: grill-monitoring
  labels:
    app.kubernetes.io/name: grill-monitoring
    app.kubernetes.io/part-of: homelab
data:
  # Service Discovery
  DEVICE_SERVICE_URL: "http://device-service:8080"
  TEMPERATURE_SERVICE_URL: "http://temperature-service:8080"
  HOMEASSISTANT_SERVICE_URL: "http://homeassistant-service:8080"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8080"
  
  # Database Configuration
  DB_HOST: "postgresql-service"
  DB_PORT: "5432"
  DB_NAME: "grill_monitoring"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Monitoring Configuration
  SYNC_INTERVAL: "300"  # 5 minutes in seconds
  TEMPERATURE_THRESHOLD_HIGH: "250"  # Fahrenheit
  TEMPERATURE_THRESHOLD_LOW: "32"    # Fahrenheit
  
  # Logging Configuration
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
---
apiVersion: v1
kind: Secret
metadata:
  name: grill-monitoring-secrets
  namespace: grill-monitoring
  labels:
    app.kubernetes.io/name: grill-monitoring
    app.kubernetes.io/part-of: homelab
type: Opaque
stringData:
  # ThermoWorks API
  THERMOWORKS_API_KEY: "your-api-key-here"
  
  # Home Assistant
  HOMEASSISTANT_URL: "http://homeassistant:8123"
  HOMEASSISTANT_TOKEN: "your-long-lived-token-here"
  
  # Database Credentials
  DB_USERNAME: "grill_monitor"
  DB_PASSWORD: "secure-password-here"
  
  # Redis Password
  REDIS_PASSWORD: "redis-password-here"