apiVersion: apps/v1
kind: Deployment
metadata:
  name: grill-stats
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grill-stats
  template:
    metadata:
      labels:
        app: grill-stats
    spec:
      imagePullSecrets:
      - name: gitea-registry
      containers:
      - name: grill-stats
        image: gitea.lab.apj.dev/lordmuffin/grill-stats:latest
        ports:
        - containerPort: 5000
        env:
        - name: THERMOWORKS_API_KEY
          valueFrom:
            secretKeyRef:
              name: grill-stats-secrets
              key: thermoworks-api-key
        - name: HOMEASSISTANT_URL
          valueFrom:
            configMapKeyRef:
              name: grill-stats-config
              key: homeassistant-url
        - name: HOMEASSISTANT_TOKEN
          valueFrom:
            secretKeyRef:
              name: grill-stats-secrets
              key: homeassistant-token
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: grill-stats-db-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grill-stats-db-credentials
              key: password
        - name: POSTGRES_DB
          value: grillstats
        - name: DATABASE_URL
          value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@grill-stats-db:5432/$(POSTGRES_DB)
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5