apiVersion: v1
kind: Namespace
metadata:
  name: grill-monitoring
  labels:
    name: grill-monitoring
    app.kubernetes.io/name: grill-monitoring
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: grill-monitoring-quota
  namespace: grill-monitoring
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "10"
    services: "10"
    persistentvolumeclaims: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: grill-monitoring-limits
  namespace: grill-monitoring
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container