apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grill-stats-db-pvc
  namespace: services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path  # Use your cluster's storage class