apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backup-rolebinding
  namespace: grill-stats
subjects:
- kind: ServiceAccount
  name: backup-sa
  namespace: grill-stats
roleRef:
  kind: Role
  name: backup-role
  apiGroup: rbac.authorization.k8s.io
