apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-backups-pvc
  namespace: grill-stats
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
