apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - network-policies
  - service-accounts
  - rbac
  - configmaps
  - secrets
  - probes
  - monitors

commonLabels:
  app.kubernetes.io/name: grill-stats
  app.kubernetes.io/part-of: grill-stats
  app.kubernetes.io/managed-by: kustomize

namespace: grill-stats
