apiVersion: v1
kind: LimitRange
metadata:
  name: grill-stats-limits
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: grill-stats
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/managed-by: kustomize
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "250m"
      memory: "256Mi"
    type: Container
  - default:
      storage: "20Gi"
    defaultRequest:
      storage: "5Gi"
    type: PersistentVolumeClaim
