apiVersion: v1
kind: ResourceQuota
metadata:
  name: grill-stats-quota
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: grill-stats
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/managed-by: kustomize
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "20"
    pods: "50"
    services: "20"
    services.loadbalancers: "2"
    secrets: "30"
    configmaps: "30"
    ingresses.networking.k8s.io: "10"
    networkpolicies.networking.k8s.io: "20"
