apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
  namespace: grill-monitoring
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: database
spec:
  serviceName: influxdb-service
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: influxdb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: influxdb
        app.kubernetes.io/part-of: grill-stats
        app.kubernetes.io/component: database
    spec:
      containers:
      - name: influxdb
        image: influxdb:1.8-alpine
        ports:
        - containerPort: 8086
          name: influxdb
        env:
        - name: INFLUXDB_DB
          value: temperature_data
        - name: INFLUXDB_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grill-monitoring-secrets
              key: DB_USERNAME
        - name: INFLUXDB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grill-monitoring-secrets
              key: DB_PASSWORD
        - name: INFLUXDB_HTTP_AUTH_ENABLED
          value: "true"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1
            memory: 1Gi
        volumeMounts:
        - name: influxdb-data
          mountPath: /var/lib/influxdb
        readinessProbe:
          httpGet:
            path: /ping
            port: 8086
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /ping
            port: 8086
          initialDelaySeconds: 30
          periodSeconds: 20
      volumes:
      - name: influxdb-data
        persistentVolumeClaim:
          claimName: influxdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: grill-monitoring
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: database
spec:
  selector:
    app.kubernetes.io/name: influxdb
  ports:
  - port: 8086
    targetPort: influxdb
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  namespace: grill-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard