apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: device-service-pdb
  namespace: grill-stats
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: device-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: temperature-service-pdb
  namespace: grill-stats
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: temperature-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: homeassistant-service-pdb
  namespace: grill-stats
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homeassistant-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgresql-pdb
  namespace: grill-stats
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: influxdb-pdb
  namespace: grill-stats
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: influxdb