apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-service
spec:
  template:
    spec:
      containers:
      - name: device-service
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-service
spec:
  template:
    spec:
      containers:
      - name: temperature-service
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  template:
    spec:
      containers:
      - name: postgresql
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
spec:
  template:
    spec:
      containers:
      - name: influxdb
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2
            memory: 4Gi
