---
# Prod Lab Environment 1Password Connect Configuration
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prod-lab-environment-secrets-1password
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: environment
    environment: prod-lab
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/grill-stats-prod/items/prod-lab-environment-secrets"
---
# Prod Lab Environment Secrets
apiVersion: v1
kind: Secret
metadata:
  name: prod-lab-environment-secrets
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: environment
    environment: prod-lab
    managed-by: onepassword-connect
  annotations:
    onepassword.com/item-path: "vaults/grill-stats-prod/items/prod-lab-environment-secrets"
type: Opaque
stringData:
  # Environment Configuration
  environment: "prod-lab"
  debug-enabled: "false"
  log-level: "INFO"
  
  # Database Configuration (Prod-specific)
  database-url: ""
  database-host: "postgresql-prod.grill-stats-prod.svc.cluster.local"
  database-port: "5432"
  database-name: "grill_stats_prod"
  database-user: ""
  database-password: ""
  
  # InfluxDB Configuration (Prod-specific)
  influxdb-url: "http://influxdb-prod.grill-stats-prod.svc.cluster.local:8086"
  influxdb-token: ""
  influxdb-org: "grill-stats-prod"
  influxdb-bucket: "temperature-data-prod"
  
  # Redis Configuration (Prod-specific)
  redis-host: "redis-prod.grill-stats-prod.svc.cluster.local"
  redis-port: "6379"
  redis-password: ""
  redis-url: ""
  
  # ThermoWorks API Configuration (Production)
  thermoworks-client-id: ""
  thermoworks-client-secret: ""
  thermoworks-base-url: "https://api.thermoworks.com"
  thermoworks-auth-url: "https://auth.thermoworks.com"
  
  # Service URLs (Prod-specific)
  auth-service-url: "http://auth-service-prod.grill-stats-prod.svc.cluster.local:8082"
  device-service-url: "http://device-service-prod.grill-stats-prod.svc.cluster.local:8080"
  temperature-service-url: "http://temperature-service-prod.grill-stats-prod.svc.cluster.local:8081"
  historical-service-url: "http://historical-service-prod.grill-stats-prod.svc.cluster.local:8083"
  encryption-service-url: "http://encryption-service-prod.grill-stats-prod.svc.cluster.local:8084"
  
  # JWT Configuration (Prod-specific)
  jwt-secret: ""
  jwt-expiration: "3600"
  
  # Production Settings
  dev-tools-enabled: "false"
  swagger-enabled: "false"
  metrics-enabled: "true"
  profiling-enabled: "false"
  
  # Rate Limiting (Strict for Prod)
  rate-limit-enabled: "true"
  rate-limit-requests: "1000"
  rate-limit-window: "3600"
  
  # Home Assistant Configuration (Prod)
  homeassistant-url: ""
  homeassistant-token: ""
  homeassistant-ssl-verify: "true"
  
  # Vault Configuration (Prod)
  vault-url: "http://vault-prod.grill-stats-prod.svc.cluster.local:8200"
  vault-token: ""
  vault-namespace: "grill-stats-prod"
  
  # Security Configuration
  security-hardening-enabled: "true"
  ssl-enabled: "true"
  tls-min-version: "1.2"
  
  # Backup Configuration
  backup-enabled: "true"
  backup-retention-days: "30"
  backup-schedule: "0 2 * * *"
  
  # Monitoring Configuration
  monitoring-enabled: "true"
  alerting-enabled: "true"
  health-check-strict: "true"
---
# Prod Lab Database Users 1Password Connect Configuration
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prod-lab-database-users-1password
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: database
    environment: prod-lab
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/grill-stats-prod/items/prod-lab-database-users"
---
# Prod Lab Database Users Secrets
apiVersion: v1
kind: Secret
metadata:
  name: prod-lab-database-users
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: database
    environment: prod-lab
    managed-by: onepassword-connect
  annotations:
    onepassword.com/item-path: "vaults/grill-stats-prod/items/prod-lab-database-users"
type: Opaque
stringData:
  # PostgreSQL Users (Prod)
  postgres-admin-user: "postgres"
  postgres-admin-password: ""
  
  # Service-specific Users (Prod)
  auth-service-user: "auth_service_prod"
  auth-service-password: ""
  device-service-user: "device_service_prod"
  device-service-password: ""
  encryption-service-user: "encryption_service_prod"
  encryption-service-password: ""
  historical-service-user: "historical_service_prod"
  historical-service-password: ""
  
  # Read-only Users (Prod)
  readonly-user: "readonly_prod"
  readonly-password: ""
  
  # Backup Users (Prod)
  backup-user: "backup_prod"
  backup-password: ""
  
  # InfluxDB Users (Prod)
  influxdb-admin-user: "admin"
  influxdb-admin-password: ""
  influxdb-admin-token: ""
  
  # Service-specific InfluxDB Tokens (Prod)
  temperature-service-token: ""
  historical-service-token: ""
  web-ui-token: ""
  
  # Redis Configuration (Prod)
  redis-password: ""
  
  # TimescaleDB Users (Prod)
  timescale-admin-user: "timescale_admin"
  timescale-admin-password: ""
  timescale-user: "timescale_prod"
  timescale-password: ""
  timescale-backup-user: "timescale_backup"
  timescale-backup-password: ""
---
# Prod Lab Security Secrets 1Password Connect Configuration
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prod-lab-security-secrets-1password
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: security
    environment: prod-lab
    managed-by: onepassword-connect
spec:
  itemPath: "vaults/grill-stats-prod/items/prod-lab-security-secrets"
---
# Prod Lab Security Secrets
apiVersion: v1
kind: Secret
metadata:
  name: prod-lab-security-secrets
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: security
    environment: prod-lab
    managed-by: onepassword-connect
  annotations:
    onepassword.com/item-path: "vaults/grill-stats-prod/items/prod-lab-security-secrets"
type: Opaque
stringData:
  # TLS/SSL Certificates
  tls-cert: ""
  tls-key: ""
  tls-ca: ""
  
  # API Keys for External Services
  external-api-key: ""
  webhook-secret: ""
  
  # Encryption Keys
  encryption-key: ""
  signing-key: ""
  
  # Security Tokens
  security-token: ""
  csrf-token: ""
  
  # Monitoring Keys
  monitoring-api-key: ""
  alerting-webhook-key: ""