apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: grill-stats-secrets-prod-lab
  annotations:
    config.kubernetes.io/local-config: "true"

namespace: grill-stats-prod

# Base resources from parent directory
resources:
  - ../

  # Prod-lab specific resources
  - environment-secrets-1password.yaml
  - rbac-prod-1password.yaml

commonLabels:
  app.kubernetes.io/name: grill-stats
  app.kubernetes.io/component: secrets
  app.kubernetes.io/part-of: grill-stats-platform
  app.kubernetes.io/managed-by: onepassword-connect
  app.kubernetes.io/version: prod-lab
  environment: prod-lab
  onepassword.com/managed: "true"

commonAnnotations:
  config.kubernetes.io/local-config: "true"
  onepassword.com/vault: "grill-stats-prod"
  onepassword.com/environment: "prod-lab"
  onepassword.com/version: "v1.0.0"
  deployment.kubernetes.io/revision: "1"

# Override namespace for prod environment
namespace: grill-stats-prod

# Configuration for prod environment
configMapGenerator:
- name: grill-stats-secrets-config
  behavior: merge
  literals:
    - environment=prod-lab
    - vault-name=grill-stats-prod
    - secret-rotation-days=90
    - backup-enabled=true
    - monitoring-enabled=true
    - audit-enabled=true
    - debug-enabled=false
    - log-level=INFO
    - security-hardening=true

# Secret generator for prod-specific configurations
secretGenerator:
- name: grill-stats-common-config
  behavior: merge
  literals:
    - log-level=INFO
    - health-check-interval=30
    - metrics-port=9090
    - debug-enabled=false
    - dev-mode=false
    - security-hardening=true

# Patches for prod environment
patchesStrategicMerge:
- |
  apiVersion: v1
  kind: Secret
  metadata:
    name: auth-service-secrets
    namespace: grill-stats-prod
  stringData:
    debug-enabled: "false"
    log-level: "INFO"
    rate-limit-enabled: "true"
    dev-mode: "false"
    security-hardening: "true"
    jwt-expiration: "3600"
- |
  apiVersion: v1
  kind: Secret
  metadata:
    name: device-service-secrets
    namespace: grill-stats-prod
  stringData:
    debug-enabled: "false"
    log-level: "INFO"
    device-discovery-interval: "60"
    dev-mode: "false"
    security-hardening: "true"
    device-timeout: "30"
- |
  apiVersion: v1
  kind: Secret
  metadata:
    name: temperature-service-secrets
    namespace: grill-stats-prod
  stringData:
    debug-enabled: "false"
    log-level: "INFO"
    temperature-sampling-interval: "5"
    dev-mode: "false"
    security-hardening: "true"
    temperature-retention-days: "90"
- |
  apiVersion: v1
  kind: Secret
  metadata:
    name: historical-data-service-secrets
    namespace: grill-stats-prod
  stringData:
    debug-enabled: "false"
    log-level: "INFO"
    query-timeout: "300"
    dev-mode: "false"
    security-hardening: "true"
    data-retention-days: "365"
- |
  apiVersion: v1
  kind: Secret
  metadata:
    name: encryption-service-secrets
    namespace: grill-stats-prod
  stringData:
    debug-enabled: "false"
    log-level: "INFO"
    audit-enabled: "true"
    dev-mode: "false"
    security-hardening: "true"
    audit-retention-days: "180"
- |
  apiVersion: v1
  kind: Secret
  metadata:
    name: web-ui-secrets
    namespace: grill-stats-prod
  stringData:
    debug-enabled: "false"
    dev-mode: "false"
    hot-reload: "false"
    analytics-enabled: "false"
    security-headers: "true"
    csp-enabled: "true"

# Replacements for prod environment
replacements:
- source:
    kind: ConfigMap
    name: grill-stats-secrets-config
    fieldPath: data.vault-name
  targets:
  - select:
      kind: OnePasswordItem
    fieldPaths:
    - spec.itemPath
    options:
      delimiter: "/"
      index: 1

# JSON patches for prod-specific modifications
patchesJson6902:
- target:
    group: onepassword.com
    version: v1
    kind: OnePasswordItem
    name: auth-service-secrets-1password
  patch: |-
    - op: replace
      path: /spec/itemPath
      value: vaults/grill-stats-prod/items/auth-service-secrets
- target:
    group: onepassword.com
    version: v1
    kind: OnePasswordItem
    name: device-service-secrets-1password
  patch: |-
    - op: replace
      path: /spec/itemPath
      value: vaults/grill-stats-prod/items/device-service-secrets
- target:
    group: onepassword.com
    version: v1
    kind: OnePasswordItem
    name: temperature-service-secrets-1password
  patch: |-
    - op: replace
      path: /spec/itemPath
      value: vaults/grill-stats-prod/items/temperature-service-secrets
- target:
    group: onepassword.com
    version: v1
    kind: OnePasswordItem
    name: historical-data-service-secrets-1password
  patch: |-
    - op: replace
      path: /spec/itemPath
      value: vaults/grill-stats-prod/items/historical-data-service-secrets
- target:
    group: onepassword.com
    version: v1
    kind: OnePasswordItem
    name: encryption-service-secrets-1password
  patch: |-
    - op: replace
      path: /spec/itemPath
      value: vaults/grill-stats-prod/items/encryption-service-secrets
- target:
    group: onepassword.com
    version: v1
    kind: OnePasswordItem
    name: web-ui-secrets-1password
  patch: |-
    - op: replace
      path: /spec/itemPath
      value: vaults/grill-stats-prod/items/web-ui-secrets
- target:
    group: onepassword.com
    version: v1
    kind: OnePasswordItem
    name: postgresql-secrets-1password
  patch: |-
    - op: replace
      path: /spec/itemPath
      value: vaults/grill-stats-prod/items/postgresql-secrets
- target:
    group: onepassword.com
    version: v1
    kind: OnePasswordItem
    name: influxdb-secrets-1password
  patch: |-
    - op: replace
      path: /spec/itemPath
      value: vaults/grill-stats-prod/items/influxdb-secrets
- target:
    group: onepassword.com
    version: v1
    kind: OnePasswordItem
    name: redis-secrets-1password
  patch: |-
    - op: replace
      path: /spec/itemPath
      value: vaults/grill-stats-prod/items/redis-secrets
- target:
    group: onepassword.com
    version: v1
    kind: OnePasswordItem
    name: timescaledb-secrets-1password
  patch: |-
    - op: replace
      path: /spec/itemPath
      value: vaults/grill-stats-prod/items/timescaledb-secrets

# Generators for prod environment
generators:
- |
  apiVersion: builtin
  kind: ConfigMapGenerator
  metadata:
    name: prod-environment-config
  literals:
    - environment=prod-lab
    - cluster-name=grill-stats-prod
    - region=homelab-prod
    - deployment-time=$(date -u +%Y%m%d%H%M%S)
    - debug-enabled=false
    - log-level=INFO
    - security-hardening=true

# Validation rules for prod environment
validators:
- |
  apiVersion: builtin
  kind: ValidatorTransformer
  metadata:
    name: prod-secret-validator
  rules:
  - apiVersion: v1
    kind: Secret
    jsonSchema:
      type: object
      properties:
        metadata:
          type: object
          properties:
            labels:
              type: object
              required:
              - app.kubernetes.io/name
              - app.kubernetes.io/component
              - environment
              - managed-by
              properties:
                environment:
                  enum:
                  - prod-lab
            annotations:
              type: object
              required:
              - onepassword.com/item-path
              - onepassword.com/environment
              properties:
                onepassword.com/environment:
                  enum:
                  - prod-lab
        stringData:
          type: object
          properties:
            debug-enabled:
              enum:
              - "false"
            dev-mode:
              enum:
              - "false"
            log-level:
              enum:
              - "INFO"
              - "WARN"
              - "ERROR"
      required:
      - metadata

# Resource limits for prod environment
resourceLimits:
- memory: 512Mi
  cpu: 500m
  selector:
    matchLabels:
      app.kubernetes.io/component: secrets
