---
# Prod Lab Environment Secrets Management Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grill-stats-secrets-manager-prod
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: secrets
    environment: prod-lab
    managed-by: onepassword-connect
  annotations:
    onepassword.com/service-account: "true"
    onepassword.com/environment: "prod-lab"
---
# Prod Lab Environment Secrets Management Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grill-stats-secrets-manager-prod
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: secrets
    environment: prod-lab
    managed-by: onepassword-connect
rules:
# Secret management (prod environment) - more restrictive
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# OnePassword Connect resources (prod environment)
- apiGroups: ["onepassword.com"]
  resources: ["onepassworditems"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# ConfigMap access for configuration (read-only in prod)
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Events for auditing
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
# Prod Lab Environment Secrets Management RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grill-stats-secrets-manager-prod
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: secrets
    environment: prod-lab
    managed-by: onepassword-connect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grill-stats-secrets-manager-prod
subjects:
- kind: ServiceAccount
  name: grill-stats-secrets-manager-prod
  namespace: grill-stats-prod
---
# Prod Lab Auth Service Secrets Access Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-secrets-prod
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: auth-service
    environment: prod-lab
    managed-by: onepassword-connect
---
# Prod Lab Auth Service Secrets Access Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: auth-service-secrets-prod
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: auth-service
    environment: prod-lab
    managed-by: onepassword-connect
rules:
# Auth service specific secrets only
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: 
    - "prod-lab-environment-secrets"
    - "prod-lab-database-users"
    - "auth-service-secrets"
    - "postgresql-secrets"
    - "redis-secrets"
  verbs: ["get", "list", "watch"]
# OnePassword Connect resources for auth service
- apiGroups: ["onepassword.com"]
  resources: ["onepassworditems"]
  resourceNames:
    - "prod-lab-environment-secrets-1password"
    - "prod-lab-database-users-1password"
    - "auth-service-secrets-1password"
  verbs: ["get", "list", "watch"]
---
# Prod Lab Auth Service Secrets Access RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auth-service-secrets-prod
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: auth-service
    environment: prod-lab
    managed-by: onepassword-connect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: auth-service-secrets-prod
subjects:
- kind: ServiceAccount
  name: auth-service-secrets-prod
  namespace: grill-stats-prod
---
# Prod Lab Device Service Secrets Access Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: device-service-secrets-prod
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: device-service
    environment: prod-lab
    managed-by: onepassword-connect
---
# Prod Lab Device Service Secrets Access Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: device-service-secrets-prod
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: device-service
    environment: prod-lab
    managed-by: onepassword-connect
rules:
# Device service specific secrets only
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: 
    - "prod-lab-environment-secrets"
    - "prod-lab-database-users"
    - "device-service-secrets"
    - "postgresql-secrets"
    - "redis-secrets"
  verbs: ["get", "list", "watch"]
# OnePassword Connect resources for device service
- apiGroups: ["onepassword.com"]
  resources: ["onepassworditems"]
  resourceNames:
    - "prod-lab-environment-secrets-1password"
    - "prod-lab-database-users-1password"
    - "device-service-secrets-1password"
  verbs: ["get", "list", "watch"]
---
# Prod Lab Device Service Secrets Access RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: device-service-secrets-prod
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: device-service
    environment: prod-lab
    managed-by: onepassword-connect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: device-service-secrets-prod
subjects:
- kind: ServiceAccount
  name: device-service-secrets-prod
  namespace: grill-stats-prod
---
# Prod Lab Temperature Service Secrets Access Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: temperature-service-secrets-prod
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: temperature-service
    environment: prod-lab
    managed-by: onepassword-connect
---
# Prod Lab Temperature Service Secrets Access Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: temperature-service-secrets-prod
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: temperature-service
    environment: prod-lab
    managed-by: onepassword-connect
rules:
# Temperature service specific secrets only
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: 
    - "prod-lab-environment-secrets"
    - "prod-lab-database-users"
    - "temperature-service-secrets"
    - "influxdb-secrets"
    - "redis-secrets"
  verbs: ["get", "list", "watch"]
# OnePassword Connect resources for temperature service
- apiGroups: ["onepassword.com"]
  resources: ["onepassworditems"]
  resourceNames:
    - "prod-lab-environment-secrets-1password"
    - "prod-lab-database-users-1password"
    - "temperature-service-secrets-1password"
  verbs: ["get", "list", "watch"]
---
# Prod Lab Temperature Service Secrets Access RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: temperature-service-secrets-prod
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: temperature-service
    environment: prod-lab
    managed-by: onepassword-connect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: temperature-service-secrets-prod
subjects:
- kind: ServiceAccount
  name: temperature-service-secrets-prod
  namespace: grill-stats-prod
---
# Prod Lab Historical Data Service Secrets Access Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: historical-data-service-secrets-prod
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: historical-data-service
    environment: prod-lab
    managed-by: onepassword-connect
---
# Prod Lab Historical Data Service Secrets Access Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: historical-data-service-secrets-prod
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: historical-data-service
    environment: prod-lab
    managed-by: onepassword-connect
rules:
# Historical data service specific secrets only
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: 
    - "prod-lab-environment-secrets"
    - "prod-lab-database-users"
    - "historical-data-service-secrets"
    - "timescaledb-secrets"
    - "influxdb-secrets"
    - "redis-secrets"
  verbs: ["get", "list", "watch"]
# OnePassword Connect resources for historical data service
- apiGroups: ["onepassword.com"]
  resources: ["onepassworditems"]
  resourceNames:
    - "prod-lab-environment-secrets-1password"
    - "prod-lab-database-users-1password"
    - "historical-data-service-secrets-1password"
  verbs: ["get", "list", "watch"]
---
# Prod Lab Historical Data Service Secrets Access RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: historical-data-service-secrets-prod
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: historical-data-service
    environment: prod-lab
    managed-by: onepassword-connect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: historical-data-service-secrets-prod
subjects:
- kind: ServiceAccount
  name: historical-data-service-secrets-prod
  namespace: grill-stats-prod
---
# Prod Lab Encryption Service Secrets Access Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: encryption-service-secrets-prod
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: encryption-service
    environment: prod-lab
    managed-by: onepassword-connect
---
# Prod Lab Encryption Service Secrets Access Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: encryption-service-secrets-prod
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: encryption-service
    environment: prod-lab
    managed-by: onepassword-connect
rules:
# Encryption service specific secrets only
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: 
    - "prod-lab-environment-secrets"
    - "prod-lab-database-users"
    - "prod-lab-security-secrets"
    - "encryption-service-secrets"
    - "postgresql-secrets"
    - "redis-secrets"
  verbs: ["get", "list", "watch"]
# OnePassword Connect resources for encryption service
- apiGroups: ["onepassword.com"]
  resources: ["onepassworditems"]
  resourceNames:
    - "prod-lab-environment-secrets-1password"
    - "prod-lab-database-users-1password"
    - "prod-lab-security-secrets-1password"
    - "encryption-service-secrets-1password"
  verbs: ["get", "list", "watch"]
---
# Prod Lab Encryption Service Secrets Access RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: encryption-service-secrets-prod
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: encryption-service
    environment: prod-lab
    managed-by: onepassword-connect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: encryption-service-secrets-prod
subjects:
- kind: ServiceAccount
  name: encryption-service-secrets-prod
  namespace: grill-stats-prod
---
# Prod Lab Web UI Service Secrets Access Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-ui-secrets-prod
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: web-ui
    environment: prod-lab
    managed-by: onepassword-connect
---
# Prod Lab Web UI Service Secrets Access Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: web-ui-secrets-prod
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: web-ui
    environment: prod-lab
    managed-by: onepassword-connect
rules:
# Web UI service specific secrets only
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: 
    - "prod-lab-environment-secrets"
    - "web-ui-secrets"
  verbs: ["get", "list", "watch"]
# OnePassword Connect resources for web UI service
- apiGroups: ["onepassword.com"]
  resources: ["onepassworditems"]
  resourceNames:
    - "prod-lab-environment-secrets-1password"
    - "web-ui-secrets-1password"
  verbs: ["get", "list", "watch"]
---
# Prod Lab Web UI Service Secrets Access RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-ui-secrets-prod
  namespace: grill-stats-prod
  labels:
    app: grill-stats
    component: web-ui
    environment: prod-lab
    managed-by: onepassword-connect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-ui-secrets-prod
subjects:
- kind: ServiceAccount
  name: web-ui-secrets-prod
  namespace: grill-stats-prod