apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace
- databases
- core-services
- supporting-services
- ingress
- operators
- vault
- external-services
- monitoring
