apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-exporter
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: influxdb-exporter
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: influxdb-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: influxdb-exporter
        app.kubernetes.io/part-of: grill-stats
        app.kubernetes.io/component: monitoring
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9122"
    spec:
      containers:
      - name: influxdb-exporter
        image: quay.io/prometheuscommunity/influxdb-exporter:v0.11.3
        imagePullPolicy: IfNotPresent
        args:
        - "--influx.server=http://influxdb:8086"
        - "--influx.username=$(INFLUXDB_USERNAME)"
        - "--influx.password=$(INFLUXDB_PASSWORD)"
        - "--influx.db=$(INFLUXDB_DATABASE)"
        - "--web.listen-address=:9122"
        - "--web.telemetry-path=/metrics"
        env:
        - name: INFLUXDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: influxdb-user
        - name: INFLUXDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: influxdb-password
        - name: INFLUXDB_DATABASE
          value: grill_stats
        ports:
        - name: metrics
          containerPort: 9122
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
