apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: redis-exporter
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: monitoring
spec:
  selector:
    app.kubernetes.io/name: redis-exporter
  ports:
  - name: metrics
    port: 9121
    targetPort: metrics
  type: ClusterIP
