---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-environment-config
  namespace: grill-stats-dev
data:
  ENVIRONMENT: "dev"
  VAULT_ADDR: "https://vault.vault.svc.cluster.local:8200"
  VAULT_SKIP_VERIFY: "true"
  VAULT_TRANSIT_PATH: "transit"
  VAULT_AUTH_PATH: "auth/kubernetes"
  VAULT_ROLE_PREFIX: "grill-stats"
  AUTO_ROTATE_ENABLED: "true"
  AUDIT_LOGGING_ENABLED: "true"
  MONITORING_ENABLED: "true"
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS_PER_SECOND: "50"  # Lower limit for dev
  RATE_LIMIT_BURST: "100"
  TOKEN_RENEWAL_THRESHOLD: "3600"
  TOKEN_MAX_TTL: "86400"
  ENCRYPTION_BATCH_SIZE: "50"  # Smaller batch size for dev
  ENCRYPTION_TIMEOUT: "10s"
  KEY_ROTATION_NOTIFICATION_ENABLED: "false"  # Disable notifications in dev
  BACKUP_ENABLED: "false"  # Disable backups in dev
  BACKUP_RETENTION_DAYS: "30"
  KEY_ROTATION_INTERVAL: "720h"  # 30 days for dev
  MAX_KEY_AGE_DAYS: "30"
  DRY_RUN: "false"
  LOG_LEVEL: "DEBUG"
---
apiVersion: v1
kind: Namespace
metadata:
  name: grill-stats-dev
  labels:
    name: grill-stats-dev
    environment: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent
  namespace: grill-stats-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: vault-agent
        env:
        - name: ENVIRONMENT
          value: "dev"
        - name: VAULT_ADDR
          value: "https://vault.vault.svc.cluster.local:8200"
        - name: VAULT_SKIP_VERIFY
          value: "true"
        - name: LOG_LEVEL
          value: "DEBUG"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: key-rotation-cronjob
  namespace: grill-stats-dev
spec:
  schedule: "0 2 * * 1"  # Weekly on Monday at 2 AM for dev
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: key-rotation
            env:
            - name: ENVIRONMENT
              value: "dev"
            - name: VAULT_ADDR
              value: "https://vault.vault.svc.cluster.local:8200"
            - name: ROTATION_INTERVAL_HOURS
              value: "720"  # 30 days
            - name: MAX_KEY_AGE_DAYS
              value: "30"
            - name: DRY_RUN
              value: "false"
            - name: LOG_LEVEL
              value: "DEBUG"
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "100m"
