apiVersion: v1
kind: ConfigMap
metadata:
  name: data-processing-service-config
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: data-processing-service
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/managed-by: kustomize
data:
  # Service-specific configuration
  API_PORT: "8080"
  HEALTH_CHECK_PORT: "8081"
  SERVICE_NAME: "data-processing-service"
  
  # Analytics configuration
  ENABLE_REALTIME_ANALYTICS: "true"
  ENABLE_BATCH_ANALYTICS: "true"
  BATCH_PROCESSING_INTERVAL_MINUTES: "60"
  
  # Machine learning model configuration
  ML_MODEL_PATH: "/models"
  ANOMALY_DETECTION_THRESHOLD: "0.8"
  PREDICTION_CONFIDENCE_THRESHOLD: "0.7"
  
  # Data storage configuration
  ANALYTICS_DATABASE: "analytics"
  ANALYTICS_RETENTION_DAYS: "365"
  
  # Kafka configuration
  KAFKA_CONSUMER_GROUP: "data-processing-service"
  KAFKA_TEMPERATURE_TOPIC: "temperature-events"
  KAFKA_ANALYTICS_TOPIC: "analytics-events"
  
  # Feature flags
  ENABLE_ANOMALY_DETECTION: "true"
  ENABLE_PREDICTIVE_MODELING: "true"
  ENABLE_PATTERN_RECOGNITION: "true"
  ENABLE_REPORTING: "true"