apiVersion: v1
kind: ConfigMap
metadata:
  name: temperature-service-config
  namespace: grill-stats
  labels:
    app.kubernetes.io/name: temperature-service
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/managed-by: kustomize
data:
  # Service-specific configuration
  API_PORT: "8080"
  HEALTH_CHECK_PORT: "8081"
  SERVICE_NAME: "temperature-service"

  # Temperature data collection configuration
  TEMPERATURE_POLL_INTERVAL_SECONDS: "60"
  TEMPERATURE_DATA_RETENTION_DAYS: "365"

  # Time-series database configuration
  INFLUXDB_MEASUREMENT: "temperature_readings"
  INFLUXDB_RETENTION_POLICY: "one_year"

  # Real-time streaming configuration
  ENABLE_WEBSOCKETS: "true"
  WEBSOCKET_PORT: "8082"

  # Kafka configuration
  KAFKA_CONSUMER_GROUP: "temperature-service"
  KAFKA_TEMPERATURE_TOPIC: "temperature-events"

  # Data processing
  ENABLE_ANOMALY_DETECTION: "true"
  ANOMALY_THRESHOLD: "20.0"
