apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grill-stats-platform
  namespace: argocd
  labels:
    app.kubernetes.io/name: grill-stats-platform
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: grill-stats

  source:
    repoURL: https://github.com/lordmuffin/grill-stats.git
    targetRevision: main
    path: apps/argocd/grill-stats/base

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=false  # ArgoCD namespace should already exist
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10

  info:
  - name: Description
    value: App-of-Apps for complete grill-stats platform deployment
  - name: Environment
    value: prod-lab
  - name: Repository
    value: https://github.com/lordmuffin/grill-stats.git
  - name: Documentation
    value: https://github.com/lordmuffin/grill-stats/blob/main/kustomize/README.md

  # Health check configuration
  ignoreDifferences:
  - group: argoproj.io
    kind: Application
    jsonPointers:
    - /status
    - /metadata/generation

  # Notification configuration
  operation:
    initiatedBy:
      automated: true
    info:
    - name: Reason
      value: Automated sync by ArgoCD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grill-stats-platform-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: grill-stats-platform-dev
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/environment: dev-lab
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: grill-stats

  source:
    repoURL: https://github.com/lordmuffin/grill-stats.git
    targetRevision: develop  # Use develop branch for dev environment
    path: apps/argocd/grill-stats/overlays/dev-lab

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 5  # Keep fewer revisions for dev

  info:
  - name: Description
    value: Development environment app-of-apps for grill-stats platform
  - name: Environment
    value: dev-lab
  - name: Repository
    value: https://github.com/lordmuffin/grill-stats.git
  - name: Branch
    value: develop

  # Health check configuration
  ignoreDifferences:
  - group: argoproj.io
    kind: Application
    jsonPointers:
    - /status
    - /metadata/generation
