apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grill-stats-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/name: grill-stats-secrets
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: secrets
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: grill-stats

  source:
    repoURL: https://github.com/lordmuffin/grill-stats.git
    targetRevision: main
    path: apps/secrets/grill-stats

  destination:
    server: https://kubernetes.default.svc
    namespace: grill-stats

  syncPolicy:
    automated:
      prune: false  # Never auto-prune secrets for safety
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 10m

  revisionHistoryLimit: 10

  info:
  - name: Description
    value: 1Password Connect secrets for grill-stats services
  - name: Environment
    value: prod-lab
  - name: Secret Management
    value: 1Password Connect Operator

  # Ignore differences in secret data for security
  ignoreDifferences:
  - group: ''
    kind: Secret
    jsonPointers:
    - /data
    - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration
  - group: 'onepassword.com'
    kind: OnePasswordItem
    jsonPointers:
    - /status
    - /metadata/generation

  # Health check configuration
  health:
    - group: 'onepassword.com'
      kind: OnePasswordItem
      check: |
        health_status = {}
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            for i, condition in ipairs(obj.status.conditions) do
              if condition.type == "Ready" and condition.status == "True" then
                health_status.status = "Healthy"
                health_status.message = "OnePasswordItem is ready"
                return health_status
              end
            end
          end
        end
        health_status.status = "Progressing"
        health_status.message = "OnePasswordItem is being processed"
        return health_status

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grill-stats-secrets-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: grill-stats-secrets-dev
    app.kubernetes.io/part-of: grill-stats
    app.kubernetes.io/component: secrets
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/environment: dev-lab
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: grill-stats

  source:
    repoURL: https://github.com/lordmuffin/grill-stats.git
    targetRevision: develop
    path: apps/secrets/grill-stats/dev-lab

  destination:
    server: https://kubernetes.default.svc
    namespace: grill-stats-dev

  syncPolicy:
    automated:
      prune: false  # Never auto-prune secrets
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 10m

  revisionHistoryLimit: 5

  info:
  - name: Description
    value: Development environment secrets for grill-stats services
  - name: Environment
    value: dev-lab
  - name: Secret Management
    value: 1Password Connect Operator

  # Ignore differences in secret data
  ignoreDifferences:
  - group: ''
    kind: Secret
    jsonPointers:
    - /data
    - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration
  - group: 'onepassword.com'
    kind: OnePasswordItem
    jsonPointers:
    - /status
    - /metadata/generation
