apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: grill-stats
  namespace: argocd
  labels:
    app.kubernetes.io/name: grill-stats
    app.kubernetes.io/part-of: grill-stats-platform
    app.kubernetes.io/managed-by: argocd
spec:
  description: ThermoWorks BBQ Monitoring Platform - GitOps managed microservices
  
  # Source repositories
  sourceRepos:
  - 'https://github.com/lordmuffin/grill-stats.git'
  - '*'  # Allow Helm charts and other repositories
  
  # Allowed destinations
  destinations:
  - namespace: grill-stats
    server: https://kubernetes.default.svc
    name: in-cluster
  - namespace: grill-stats-dev
    server: https://kubernetes.default.svc
    name: in-cluster
  - namespace: grill-stats-staging
    server: https://kubernetes.default.svc
    name: in-cluster
  - namespace: argocd
    server: https://kubernetes.default.svc
    name: in-cluster
  
  # Cluster-wide resources that can be managed
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'networking.k8s.io'
    kind: NetworkPolicy
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
  - group: 'apiextensions.k8s.io'
    kind: CustomResourceDefinition
  - group: 'monitoring.coreos.com'
    kind: ServiceMonitor
  - group: 'monitoring.coreos.com'
    kind: PrometheusRule
  
  # Namespace-scoped resources
  namespaceResourceWhitelist:
  - group: ''
    kind: Service
  - group: ''
    kind: ServiceAccount
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: ''
    kind: PersistentVolumeClaim
  - group: 'apps'
    kind: Deployment
  - group: 'apps'
    kind: StatefulSet
  - group: 'apps'
    kind: DaemonSet
  - group: 'apps'
    kind: ReplicaSet
  - group: 'batch'
    kind: Job
  - group: 'batch'
    kind: CronJob
  - group: 'networking.k8s.io'
    kind: Ingress
  - group: 'networking.k8s.io'
    kind: NetworkPolicy
  - group: 'policy'
    kind: PodDisruptionBudget
  - group: 'autoscaling'
    kind: HorizontalPodAutoscaler
  - group: 'traefik.containo.us'
    kind: IngressRoute
  - group: 'traefik.containo.us'
    kind: Middleware
  - group: 'cert-manager.io'
    kind: Certificate
  - group: 'cert-manager.io'
    kind: Issuer
  - group: 'monitoring.coreos.com'
    kind: ServiceMonitor
  - group: 'monitoring.coreos.com'
    kind: PrometheusRule
  - group: 'onepassword.com'
    kind: OnePasswordItem
  - group: 'external-secrets.io'
    kind: SecretStore
  - group: 'external-secrets.io'
    kind: ExternalSecret
  
  # RBAC roles for project access
  roles:
  - name: developer
    description: Developer access to grill-stats applications
    policies:
    - p, proj:grill-stats:developer, applications, get, grill-stats/*, allow
    - p, proj:grill-stats:developer, applications, sync, grill-stats/*, allow
    - p, proj:grill-stats:developer, applications, action/*, grill-stats/*, allow
    - p, proj:grill-stats:developer, logs, get, grill-stats/*, allow
    - p, proj:grill-stats:developer, exec, create, grill-stats/*, allow
    groups:
    - grill-stats:developers
    
  - name: operator
    description: Operator access for production deployments
    policies:
    - p, proj:grill-stats:operator, applications, get, grill-stats/*, allow
    - p, proj:grill-stats:operator, applications, sync, grill-stats/*, allow
    - p, proj:grill-stats:operator, applications, action/*, grill-stats/*, allow
    - p, proj:grill-stats:operator, applications, override, grill-stats/*, allow
    - p, proj:grill-stats:operator, logs, get, grill-stats/*, allow
    - p, proj:grill-stats:operator, exec, create, grill-stats/*, allow
    groups:
    - grill-stats:operators
    
  - name: admin
    description: Full admin access to grill-stats platform
    policies:
    - p, proj:grill-stats:admin, applications, *, grill-stats/*, allow
    - p, proj:grill-stats:admin, repositories, *, *, allow
    - p, proj:grill-stats:admin, clusters, *, *, allow
    - p, proj:grill-stats:admin, gpgkeys, *, *, allow
    groups:
    - grill-stats:admins
    
  # Sync policies and restrictions
  syncWindows:
  - kind: allow
    schedule: '* * * * *'
    duration: 24h
    applications:
    - grill-stats-*
    manualSync: true
    
  # Prevent sync during maintenance windows
  - kind: deny
    schedule: '0 2 * * 0'  # Sunday 2 AM
    duration: 2h
    applications:
    - grill-stats-core-services-prod
    - grill-stats-databases-prod
    manualSync: false
    
  # Orphaned resources policy
  orphanedResources:
    warn: true
    ignore:
    - group: ''
      kind: Secret
      name: '*-1password-*'
    - group: 'monitoring.coreos.com'
      kind: ServiceMonitor
      name: '*-metrics'
      
  # Signature verification
  signatureKeys:
  - keyID: 4AEE18F83AFDEB23  # Example key ID for signed commits